export const initialForm = {
  deal: '',
  propertyType: '',
  commercialType: '',
  bhk: '',
  bathrooms: '',
  balconies: '1',
  carpetArea: '',
  builtUp: '',
  superBuiltUp: '',
  plotArea: '',
  floorsInHouse: '',
  homeTypeLabel: 'Flat',
  gatedCommunity: false,
  attachedBath: '',
  occupants: '',
  noticePeriodDays: '',
  lockInMonths: '',
  maintenanceBilling: '',
  electricityBilling: '',
  washrooms: '',
  shellType: '',
  parkingSpaces: '',
  pantry: false,
  camCharges: '',
  suitableFor: [],
  fixtures: [],
  gstOnRent: '',
  fitOutMonths: '',
  escalationPct: '',
  tenancyStatus: '',
  inPlaceRent: '',
  leaseExpiry: '',
  seatCount: '',
  frontage: '',
  floorLoad: '',
  clearHeight: '',
  sanctionedPower: '',
  dockCount: '',
  areaUnit: 'sqft',
  plotLength: '',
  plotWidth: '',
  openSides: '',
  roadWidth: '',
  cornerPlot: false,
  boundaryWall: false,
  plotZone: '',
  /* A boolean could not tell "still agricultural" from "never asked", and had no way at all to
   * say deemed-NA. */
  naStatus: '',
  waterSource: '',
  electricity: false,
  roadAccess: false,
  otherRights: '',
  buyerEligibility: '',
  floor: '',
  totalFloors: '',
  facing: '',
  overlooking: '',
  age: '',
  furnishing: 'unfurnished',
  furniture: [],
  locality: '',
  flatNumber: '',
  tower: '',
  society: '',
  // Society ENTITY binding (societies.js / community-minted). Empty when the
  // lister typed a name without picking/creating a society (legacy-safe).
  societyId: '',
  street: '',
  landmark: '',
  pincode: '',
  // The electricity consumer number is unique per metered unit, so it is both the strongest dedup
  // key and the fast-track to Verified Owner. Optional, and never shown to buyers.
  electricityConsumerNo: '',
  propLat: 18.5590,
  propLng: 73.7760,
  pinPlaced: false,
  price: '',
  priceNegotiable: false,
  transactionType: '',
  /* Unanswered: this is the field the Ready-to-Move / Under-Construction facet is built from, so a pre-selected
     default would make the required check unfailable and publish a claim as the owner's own. */
  construction: '',
  ownership: '',
  monthlyMaintenance: '',
  reraId: '',
  loanAvailable: '',
  monthlyRent: '',
  deposit: '',
  // Unstated. Defaulting to 'included' printed "Maintenance: Included" on the detail page of every
  // rental whose owner never touched the control, beside the figures they did give.
  rentMaintMode: '',
  rentMaintenance: '',
  availableFrom: '',
  preferredTenants: [],
  vegOnly: false,
  petsAllowed: false,
  petsPolicy: '',
  foodPref: 'any',
  agreementDuration: '11',
  lockIn: '0',
  noticePeriod: '1',
  bestTimeToCall: 'anytime',
  title: '',
  description: '',
  youtubeId: '',
  amenities: [],
  roomType: '',
  rentShare: '',
  lookingFor: 'any',
  lifestyle: [],
  note: '',
  // Who is listing the room: an 'owner' lists their own flat, a 'tenant' is a sitting flatmate
  // seeking a replacement and self-attests a registered agreement for Ops consent.
  hostRole: 'owner',
  agreementDeclared: false,
  agreementDoc: null,
  ownerConsentMobile: '',
  ownerConsent: false,
};
