/* ---------- default form state ---------- */
export const initialForm = {
  deal: 'buy',
  propertyType: '',
  commercialType: '',
  // Smart defaults — Pune's most common configuration, pre-filled to reduce
  // friction (endowed-progress). All remain editable.
  bhk: '2',
  bathrooms: '2',
  balconies: '1',
  carpetArea: '',
  builtUp: '',
  // house types (independent / villa)
  plotArea: '',
  floorsInHouse: '',
  // A room share can be a flat or an independent house, so `propertyType` drives the physical
  // fields while `homeTypeLabel` is the exact label on the room card.
  homeTypeLabel: 'Flat',
  gatedCommunity: false,
  // flatmate washroom — is the offered room's bathroom private (attached) or a
  // shared/common one? A top question for room seekers.
  attachedBath: '',
  // commercial specifics
  washrooms: '',
  shellType: '',
  parkingSpaces: '',
  powerBackup: false,
  pantry: false,
  camCharges: '',
  suitableFor: [],
  fixtures: [],
  // land specifics (open plot / farm land)
  areaUnit: 'sqft',
  plotLength: '',
  plotWidth: '',
  openSides: '',
  roadWidth: '',
  cornerPlot: false,
  boundaryWall: false,
  plotZone: '',
  naSanctioned: false,
  waterSource: '',
  electricity: false,
  roadAccess: false,
  satbara: false,
  floor: '',
  totalFloors: '',
  facing: '',
  overlooking: '',
  age: '',
  furnishing: 'unfurnished',
  furniture: [],
  locality: '',
  flatNumber: '',
  tower: '',
  society: '',
  // Society ENTITY binding (societies.js / community-minted). Empty when the
  // lister typed a name without picking/creating a society (legacy-safe).
  societyId: '',
  street: '',
  landmark: '',
  pincode: '',
  // The electricity consumer number is unique per metered unit, so it is both the strongest dedup
  // key and the fast-track to Verified Owner. Optional, and never shown to buyers.
  electricityConsumerNo: '',
  pmcPropertyId: '',
  propLat: 18.5590,
  propLng: 73.7760,
  price: '',
  priceNegotiable: false,
  transactionType: '',
  possession: 'ready',
  ownership: '',
  monthlyMaintenance: '',
  reraId: '',
  loanAvailable: true,
  monthlyRent: '',
  deposit: '',
  rentMaintMode: 'included',
  rentMaintenance: '',
  availableFrom: '',
  preferredTenants: [],
  vegOnly: false,
  petsAllowed: false,
  petsPolicy: '',
  foodPref: 'any',
  agreementDuration: '11',
  lockIn: '0',
  noticePeriod: '1',
  description: '',
  amenities: [],
  // flatmate
  roomType: '',
  rentShare: '',
  lookingFor: 'any',
  lifestyle: [],
  note: '',
  // Who is listing the room: an 'owner' lists their own flat, a 'tenant' is a sitting flatmate
  // seeking a replacement and self-attests a registered agreement for Ops consent.
  hostRole: 'owner',
  agreementDeclared: false,
  agreementDoc: null,
  ownerConsentMobile: '',
};
