package com.punenest.api.catalog.property;

import java.time.Duration;
import java.time.Instant;

/**
 * How long ago an owner last confirmed a listing is genuinely still available.
 *
 * <p>Derived on read, never stored. Every other ranking input on a listing is a column — the
 * quality score is generated by Postgres (V94), boost is a timestamp comparison — but freshness is
 * a function of the clock, and a clock is not a column. A stored tier would be correct at the
 * instant it was written and wrong every moment after, which is the exact failure mode the whole
 * anti-staleness model exists to prevent. So the tier is computed from {@code lastConfirmedAt}
 * each time a listing is read, and the moment an owner confirms, everything re-derives.
 *
 * <p>This moves the definition off the browser (D26). It was previously in {@code lib/freshness.js}
 * and computed after the fetch, which meant two things went wrong at once: the tier could not
 * participate in search ordering, and — more seriously — {@code isDormant} was a <em>visibility</em>
 * decision being made by the client. A listing whose owner had gone dark for months was still
 * served to the browser and merely hidden there, so anything that read the API directly saw it.
 * Hiding is a server's job; the client cannot be the last line of a trust rule.
 *
 * <p>The boundaries are inclusive upper bounds, matching what the browser did to the day, so no
 * listing changes tier on the migration.
 */
public enum Freshness {

    /** Confirmed within a week. Trustworthy, "actively managed". */
    ACTIVE,

    /** Confirmed within a fortnight. Nudge the owner, tell the buyer nothing. */
    AGING,

    /** Confirmed within a month. Warn the buyer that availability is unconfirmed. */
    STALE,

    /** Over a month of silence. The owner has gone dark; hide from buyers. */
    DORMANT;

    static final int FRESH_DAYS = 7;
    static final int AGING_DAYS = 14;
    static final int STALE_DAYS = 30;

    /**
     * Classify a listing from its last confirmation, falling back to when it was posted.
     *
     * <p>The fallback is what makes this work for a listing nobody has ever confirmed — posting is
     * itself an assertion that the property is available, so a listing posted yesterday is active
     * even though {@code lastConfirmedAt} is null. A row with neither timestamp (only reachable
     * from a half-built test fixture) is treated as freshly posted rather than dormant, because
     * defaulting to the tier that <em>hides</em> a listing would turn a missing field into an
     * invisible one.
     *
     * @param lastConfirmedAt when the owner last confirmed availability, or {@code null}
     * @param createdAt when the listing was posted, or {@code null}
     * @param now the clock, passed in so this stays testable
     */
    public static Freshness of(Instant lastConfirmedAt, Instant createdAt, Instant now) {
        Instant since = lastConfirmedAt != null ? lastConfirmedAt : createdAt;
        if (since == null || now == null) {
            return ACTIVE;
        }
        long days = Math.max(0, Duration.between(since, now).toDays());
        if (days <= FRESH_DAYS) {
            return ACTIVE;
        }
        if (days <= AGING_DAYS) {
            return AGING;
        }
        if (days <= STALE_DAYS) {
            return STALE;
        }
        return DORMANT;
    }

    /** The wire form: lowercase, matching the vocabulary the client already renders. */
    public String wire() {
        return name().toLowerCase();
    }

    /** True once the owner has been silent long enough that buyers should stop seeing this. */
    public boolean hiddenFromBuyers() {
        return this == DORMANT;
    }

    /** True once the owner should be asked to confirm — anything short of {@link #ACTIVE}. */
    public boolean needsOwnerAttention() {
        return this != ACTIVE;
    }
}
