export const AMEN_ICON = {
  gym: 'sparkles', pool: 'sparkles', lift: 'building', parking: 'car-front', security: 'shield-check',
  power: 'landmark', garden: 'trees', club: 'users', play: 'paw-print',
};
export const AMEN_LABEL = {
  gym: 'Gymnasium', pool: 'Swimming Pool', lift: 'Lift', parking: 'Covered Parking', security: '24x7 Security',
  power: 'Power Backup', garden: 'Landscaped Garden', club: 'Clubhouse', play: "Kids' Play Area",
};

/* Classifies a listing into a broad category so the detail page can show only the
   fields that make sense: apartments/villas get BHK + floor + furnishing, land/plots
   get plot zone + title, commercial gets no bedroom/bathroom fields. */
const LAND_MATCHES = ['plot', 'land', 'farm'];
const COMMERCIAL_MATCHES = ['office', 'shop', 'showroom', 'retail', 'mall', 'warehouse', 'godown', 'industrial', 'factory', 'co-working', 'coworking', 'commercial'];
export function propertyKind(p) {
  const t = String(p?.type || '').toLowerCase();
  if (LAND_MATCHES.some((k) => t.includes(k))) return 'land';
  if (COMMERCIAL_MATCHES.some((k) => t.includes(k))) return 'commercial';
  return 'residential';
}

/* Maps a listing to a schematic floor-plan asset that reflects its type + BHK
   (assets generated by scripts/gen-floorplans.mjs into public/floorplans).
   Returns null for land, which never renders a floor-plan section. Used as the
   fallback so listings without an explicit `floorPlan` field still get a plan
   that matches their type instead of a single shared stock image. */
const COMMERCIAL_PLAN = {
  office: 'office', shop: 'shop', showroom: 'shop', retail: 'retail', mall: 'retail',
  warehouse: 'warehouse', godown: 'warehouse', industrial: 'industrial', factory: 'industrial',
  'co-working': 'coworking', coworking: 'coworking',
};
export function floorPlanFor(p) {
  const kind = propertyKind(p);
  if (kind === 'land') return null;
  const t = String(p?.type || '').toLowerCase();
  if (kind === 'commercial') {
    const match = Object.keys(COMMERCIAL_PLAN).find((k) => t.includes(k));
    return `/floorplans/${match ? COMMERCIAL_PLAN[match] : 'office'}.svg`;
  }
  const beds = Number(p?.bhkNum) || 0;
  if (t.includes('studio') || beds === 0) return '/floorplans/studio.svg';
  let variant = 'flat';
  if (t.includes('villa')) variant = 'villa';
  else if (t.includes('penthouse')) variant = 'penthouse';
  else if (t.includes('row')) variant = 'rowhouse';
  if (variant === 'flat') return `/floorplans/${Math.min(4, Math.max(1, beds))}bhk.svg`;
  return `/floorplans/${variant}-${Math.min(4, Math.max(2, beds))}.svg`;
}

/* Per-listing Key-Details values, as stated by the owner.
   These read `p.form.*` for listings created through "Post a property" and the corresponding
   server column otherwise. They used to fall back to a stable id-derived value, on the
   reasoning that the original HTML page "always shows Floor, Facing and Age" — but always
   showing a value and always *knowing* one are different things, and the fallback made an
   unstated attribute indistinguishable from a stated one. They now return '' and the tile
   renders "Not specified". */
import { ageOptions } from '../list-property/constants.js';
function ordinal(n) {
  const s = ['th', 'st', 'nd', 'rd'];
  const v = n % 100;
  return n + (s[(v - 20) % 10] || s[v] || s[0]);
}
const SHORT_AGE = {
  'under-construction': 'Under Const.', 'new': 'New',
  '1-5': '1–5 yrs', '5-10': '5–10 yrs', '10-15': '10–15 yrs', '15+': '15+ yrs',
};

/* The three functions below each used to end in a hash of the listing id, so a detail page
   always stated a floor, a facing direction and an age, whether or not the owner had ever
   supplied one. `facing` in particular was invented for effectively every live listing (three
   of fifty-nine rows carry the column) and printed twice — a Key Details tile and a top-four
   highlight pill — with no indication it was a guess. Facing is Vastu-weighted in this market
   and moves offers; "3rd of 14" likewise reads as surveyed fact.

   All three now return '' when nothing was stated. PropertyTabs renders an empty tile value as
   "Not specified", which is the honest answer and the one the tile guard was written for. The
   highlight pill needed a guard of its own — see useProperty.js, where an empty facing produced
   a pill reading " Facing" and consumed one of only four highlight slots. */
export function deriveFloor(p) {
  const raw = p.form?.floor || (p.floor ? String(p.floor) : '');
  if (!raw) return '';
  const total = p.form?.totalFloors || p.totalFloors;
  // `Number('N/A')` is NaN and `ordinal(NaN)` renders the literal "NaNth". Admin post-on-behalf
  // is known to emit non-numeric floor strings, so anything unparseable is passed through as
  // typed rather than decorated with an ordinal suffix it cannot have.
  const n = Number(raw);
  const label = raw === 'Ground' ? 'Ground' : (Number.isFinite(n) ? ordinal(n) : String(raw));
  return total ? `${label} of ${total}` : label;
}
export function deriveFacing(p) {
  if (p.facing) return p.facing;
  if (p.form?.facing) return p.form.facing;
  return '';
}
export function deriveAge(p) {
  const key = p.age || p.form?.age;
  if (key) return SHORT_AGE[key] || (ageOptions.find((o) => o.value === key)?.label) || key;
  if (p.construction === 'new') return 'New';
  // `ageYears` is the server's stated age in whole years (V95, nullable — null means the owner
  // never said, which is not the same as new).
  if (p.ageYears != null) return p.ageYears + (p.ageYears === 1 ? ' Year' : ' Years');
  return '';
}
