export const AMEN_ICON = {
  gym: 'sparkles', pool: 'sparkles', lift: 'building', parking: 'car-front', security: 'shield-check',
  power: 'landmark', garden: 'trees', club: 'users', play: 'paw-print',
};
export const AMEN_LABEL = {
  gym: 'Gymnasium', pool: 'Swimming Pool', lift: 'Lift', parking: 'Covered Parking', security: '24x7 Security',
  power: 'Power Backup', garden: 'Landscaped Garden', club: 'Clubhouse', play: "Kids' Play Area",
};

/* Classifies a listing into a broad category so the detail page can show only the
   fields that make sense: apartments/villas get BHK + floor + furnishing, land/plots
   get plot zone + title, commercial gets no bedroom/bathroom fields. */
const LAND_MATCHES = ['plot', 'land', 'farm'];
const COMMERCIAL_MATCHES = ['office', 'shop', 'showroom', 'retail', 'mall', 'warehouse', 'godown', 'industrial', 'factory', 'co-working', 'coworking', 'commercial'];
export function propertyKind(p) {
  const t = String(p?.type || '').toLowerCase();
  if (LAND_MATCHES.some((k) => t.includes(k))) return 'land';
  if (COMMERCIAL_MATCHES.some((k) => t.includes(k))) return 'commercial';
  return 'residential';
}

/* Maps a listing to a schematic floor-plan asset that reflects its type + BHK
   (assets generated by scripts/gen-floorplans.mjs into public/floorplans).
   Returns null for land, which never renders a floor-plan section. Used as the
   fallback so listings without an explicit `floorPlan` field still get a plan
   that matches their type instead of a single shared stock image. */
const COMMERCIAL_PLAN = {
  office: 'office', shop: 'shop', showroom: 'shop', retail: 'retail', mall: 'retail',
  warehouse: 'warehouse', godown: 'warehouse', industrial: 'industrial', factory: 'industrial',
  'co-working': 'coworking', coworking: 'coworking',
};
export function floorPlanFor(p) {
  const kind = propertyKind(p);
  if (kind === 'land') return null;
  const t = String(p?.type || '').toLowerCase();
  if (kind === 'commercial') {
    const match = Object.keys(COMMERCIAL_PLAN).find((k) => t.includes(k));
    return `/floorplans/${match ? COMMERCIAL_PLAN[match] : 'office'}.svg`;
  }
  const beds = Number(p?.bhkNum) || 0;
  if (t.includes('studio') || beds === 0) return '/floorplans/studio.svg';
  let variant = 'flat';
  if (t.includes('villa')) variant = 'villa';
  else if (t.includes('penthouse')) variant = 'penthouse';
  else if (t.includes('row')) variant = 'rowhouse';
  if (variant === 'flat') return `/floorplans/${Math.min(4, Math.max(1, beds))}bhk.svg`;
  return `/floorplans/${variant}-${Math.min(4, Math.max(2, beds))}.svg`;
}

/* Per-listing Key-Details values. Real listings created through "Post a property"
   now carry the owner's actual floor / facing / age, so we prefer those. Legacy
   seed data lacks them, so we fall back to a stable id-derived value (mirrors the
   HTML property page which always shows Floor, Facing and Age/Available). */
import { djb2Hash as hashId } from '../../../lib/hash.js';
import { ageOptions } from '../list-property/constants.js';
function ordinal(n) {
  const s = ['th', 'st', 'nd', 'rd'];
  const v = n % 100;
  return n + (s[(v - 20) % 10] || s[v] || s[0]);
}
const SHORT_AGE = {
  'under-construction': 'Under Const.', 'new': 'New',
  '1-5': '1–5 yrs', '5-10': '5–10 yrs', '10-15': '10–15 yrs', '15+': '15+ yrs',
};
const FACINGS = ['East', 'West', 'North', 'South', 'North-East', 'North-West', 'South-East'];
export function deriveFloor(p) {
  const raw = p.form?.floor || (p.floor ? String(p.floor) : '');
  if (raw) {
    const total = p.form?.totalFloors || p.totalFloors;
    const label = raw === 'Ground' ? 'Ground' : ordinal(Number(raw));
    return total ? `${label} of ${total}` : label;
  }
  const h = hashId(p.id);
  const total = 8 + (h % 15); // 8–22 storeys
  const floor = 1 + (h % total);
  return `${ordinal(floor)} of ${total}`;
}
export function deriveFacing(p) {
  if (p.facing) return p.facing;
  if (p.form?.facing) return p.form.facing;
  return FACINGS[hashId(p.id + 'f') % FACINGS.length];
}
export function deriveAge(p) {
  const key = p.age || p.form?.age;
  if (key) return SHORT_AGE[key] || (ageOptions.find((o) => o.value === key)?.label) || key;
  if (p.construction === 'new') return 'New';
  const yrs = 1 + (hashId(p.id + 'a') % 12);
  return yrs + (yrs === 1 ? ' Year' : ' Years');
}
