// ── Phosphor icons ────────────────────────────────────────────────────────────
/* Icon.jsx — maps kebab-name strings to Phosphor icons. */

import {
  Airplane, Armchair, ArrowClockwise, ArrowCounterClockwise, ArrowLeft, ArrowRight,
  ArrowUp, ArrowsOut, Bank, Barbell, Bathtub, BatteryCharging,
  Bed, Bell, BellSlash, Bookmark, Briefcase, Building,
  Buildings, Calculator, Calendar, CalendarCheck, CalendarHeart, Camera,
  Car, CaretDown, CaretLeft, CaretRight, ChartBar, ChartLine,
  ChartLineUp, Chat, ChatCircle, ChatText, Check, CheckCircle,
  Checks, Circle, CircleNotch, ClipboardText, Clock, ClockCounterClockwise,
  CloudArrowUp, Compass, Confetti, Couch, Copy, Cpu,
  CreditCard, CurrencyInr, Database, DeviceMobile, Dog, DoorOpen,
  DotsThree, Download, Envelope, Eye, FadersHorizontal, Fan,
  FileArrowUp, FileLock, FileMagnifyingGlass, FileText, Fingerprint, Fire,
  Flag, FloppyDisk, FolderLock, FolderOpen, ForkKnife, Gavel,
  Gift, Globe, GraduationCap, Hammer, HandCoins, HandHeart,
  Handshake, HardHat, Headset, Heart, House, Image,
  Info, Key, Lamp, Lifebuoy, Lightbulb, Lightning,
  LinkSimple, Lock, MagnifyingGlass, MapPin, MapTrifold, Megaphone,
  Minus, NavigationArrow, Note, Package, PaintRoller, Palette,
  PaperPlaneTilt, Paperclip, PawPrint, PenNib, Pencil, Percent,
  Phone, PhoneCall, PhoneSlash, PiggyBank, Play, PlayCircle,
  PauseCircle, Plus, PlusCircle, Question, Receipt, Repeat,
  Rocket, Rows, Ruler, Scales, SealCheck, Share,
  Shield, ShieldCheck, ShieldWarning, ShoppingBag, SignIn, SignOut,
  Signature, Sparkle, SquaresFour, Stack, Star, StarHalf,
  Sun, Table, Tag, Television, Timer, Toolbox,
  Train, Trash, Tray, Tree, TrendDown, TrendUp,
  Truck, Upload, User, UserCheck, UserCircle, UserGear,
  UserPlus, Users, UsersThree, Video, Wallet, Warehouse,
  Warning, Waves, Wind, X, XCircle, BookOpenText,
  ThumbsUp, ThumbsDown, Archive, Prohibit, DotsThreeVertical, ArrowBendUpLeft,
  WarningCircle, CloudSlash, Moon,
} from '@phosphor-icons/react';
// ── Lucide fallbacks (icons not in Phosphor) ─────────────────────────────────

import {
  // layout / nav helpers not in Phosphor
  WashingMachine, Microwave, AirVent, Refrigerator, ChevronDown, ChevronLeft,
  ChevronRight, GitCompare, LockKeyhole, RectangleVertical, LampCeiling, Blinds,
  Droplets, ShowerHead, ParkingCircle, MoveVertical, HeartHandshake, CheckCircle2,
  BadgePercent, BadgeIndianRupee, FileCheck, FileCheck2, FileClock, FileBadge,
  FolderCheck, SearchCheck, Workflow, PenLine, Milestone, ChevronsLeftRight,
  ReceiptIndianRupee, CalendarClock, CalendarDays, BedDouble, UserSearch, TicketPlus,
  Ticket, Bug, ImagePlus, Menu, Gauge, FolderPlus,
  FolderX, AlertCircle, ExternalLink,
} from 'lucide-react';
/* ───────────────────────────────────────────────────────────────────────────── Name → component map. */

const MAP = {
  // ── Navigation & UI chrome ─────────────────────────────────────────────────
  'arrow-right':         ArrowRight,
  'arrow-left':          ArrowLeft,
  'arrow-up':            ArrowUp,
  'caret-down':          CaretDown,
  'caret-left':          CaretLeft,
  'caret-right':         CaretRight,
  'chevron-down':        ChevronDown,
  'chevron-left':        ChevronLeft,
  'chevron-right':       ChevronRight,
  menu:                  Menu,
  search:                MagnifyingGlass,
  'sliders-horizontal':  FadersHorizontal,
  expand:                ArrowsOut,
  maximize:              ArrowsOut,
  'maximize-2':          ArrowsOut,
  'layout-grid':         SquaresFour,
  list:                  Rows,
  'move-vertical':       MoveVertical,
  // ── Actions ────────────────────────────────────────────────────────────────

  plus:                  Plus,
  'plus-circle':         PlusCircle,
  minus:                 Minus,
  x:                     X,
  'x-circle':            XCircle,
  check:                 Check,
  'check-circle':        CheckCircle,
  'check-circle-2':      CheckCircle2,
  'circle-check':        CheckCircle,
  'check-check':         Checks,
  'checks-square':       Checks,
  save:                  FloppyDisk,
  copy:                  Copy,
  share: Share,
  'share-2':             Share,
  download:              Download,
  upload:                Upload,
  'upload-cloud':        CloudArrowUp,
  'cloud-upload':        CloudArrowUp,
  'file-up':             FileArrowUp,
  'rotate-ccw':          ArrowCounterClockwise,
  'refresh-cw':          ArrowClockwise,
  repeat:                Repeat,
  send:                  PaperPlaneTilt,
  'trash-2':             Trash,
  // ── Auth & security ────────────────────────────────────────────────────────

  lock:                  Lock,
  'lock-keyhole':        LockKeyhole,
  fingerprint:           Fingerprint,
  shield:                Shield,
  'shield-check':        ShieldCheck,
  'shield-alert':        ShieldWarning,
  'folder-lock':         FolderLock,
  'file-lock-2':         FileLock,
  'log-in':              SignIn,
  'log-out':             SignOut,
  // ── Communication ──────────────────────────────────────────────────────────

  mail:                  Envelope,
  phone:                 Phone,
  'phone-call':          PhoneCall,
  'phone-off':           PhoneSlash,
  bell:                  Bell,
  'bell-plus':           Bell,
  'message-circle':      ChatCircle,
  'message-square':      Chat,
  'message-square-text': ChatText,
  'messages-square':     Chat,
  info:                  Info,
  'help-circle':         Question,
  headset:               Headset,
  megaphone:             Megaphone,
  // ── People ─────────────────────────────────────────────────────────────────

  user:                  User,
  'user-check':          UserCheck,
  'user-round':          UserCircle,
  'user-plus':           UserPlus,
  'user-search':         UserSearch,
  'user-cog':            UserGear,
  users:                 Users,
  'users-round':         UsersThree,
  venus:                 UserCircle,
  mars:                  UserCircle,
  // ── Property / real-estate ────────────────────────────────────────────────

  home:                  House,
  house:                 House,
  building:              Building,
  'building-2':          Buildings,
  landmark:              Bank,
  bed:                   Bed,
  'bed-double':          BedDouble,
  bath:                  Bathtub,
  sofa:                  Couch,
  armchair:              Armchair,
  'shower-head':         ShowerHead,
  ruler:                 Ruler,
  'paint-roller':        PaintRoller,
  palette:               Palette,
  'hard-hat':            HardHat,
  warehouse:             Warehouse,
  'door-open':           DoorOpen,
  key:                   Key,
  'key-round':           Key,
  'paw-print':           PawPrint,
  dog:                   Dog,
  'parking-circle':      ParkingCircle,
  // ── Finance & commerce ────────────────────────────────────────────────────

  'indian-rupee':             CurrencyInr,
  'badge-indian-rupee':       BadgeIndianRupee,
  'receipt-indian-rupee':     ReceiptIndianRupee,
  'badge-percent':            BadgePercent,
  'badge-check':              SealCheck,
  calculator:                 Calculator,
  wallet:                     Wallet,
  'credit-card':              CreditCard,
  'piggy-bank':               PiggyBank,
  percent:                    Percent,
  scale:                      Scales,
  tag:                        Tag,
  receipt:                    Receipt,
  'hand-coins':               HandCoins,
  'hand-heart':               HandHeart,
  handshake:                  Handshake,
  'heart-handshake':          HeartHandshake,
  truck:                      Truck,
  toolbox:                    Toolbox,
  package:                    Package,
  // ── Navigation & location ─────────────────────────────────────────────────

  map:                   MapTrifold,
  'map-pin':             MapPin,
  'map-pinned':          MapPin,
  navigation:            NavigationArrow,
  compass:               Compass,
  globe:                 Globe,
  flag:                  Flag,
  milestone:             Milestone,
  'train-front':         Train,
  plane:                 Airplane,
  // ── Charts & data ─────────────────────────────────────────────────────────

  'trending-up':         TrendUp,
  'trending-down':       TrendDown,
  'bar-chart-3':         ChartBar,
  'line-chart':          ChartLineUp,
  'chart-line':          ChartLine,
  database:              Database,
  'git-compare':         GitCompare,
  workflow:              Workflow,
  'chevrons-left-right': ChevronsLeftRight,
  // ── Files & documents ────────────────────────────────────────────────────

  'file-text':           FileText,
  'file-check':          FileCheck,
  'file-check-2':        FileCheck2,
  'file-pen-line':       PenLine,
  'file-signature':      Signature,
  'file-search':         FileMagnifyingGlass,
  'file-clock':          FileClock,
  'file-badge':          FileBadge,
  'folder-check':        FolderCheck,
  'search-check':        SearchCheck,
  'clipboard-list':      ClipboardText,
  paperclip:             Paperclip,
  'scroll-text':         Note,
  table:                 Table,
  // ── Editing & writing ────────────────────────────────────────────────────

  pencil:                Pencil,
  edit:                  Pencil,
  'pen-line':            PenLine,
  'pen-tool':            PenNib,
  'pan-tool':            PenNib,
  // ── Media ────────────────────────────────────────────────────────────────

  camera:                Camera,
  video:                 Video,
  image:                 Image,
  'image-plus':          ImagePlus,
  play:                  Play,
  'play-circle':         PlayCircle,
  'pause-circle':        PauseCircle,
  'undo-2':              ArrowCounterClockwise,
  tv:                    Television,

  // ── Amenities & appliances ───────────────────────────────────────────────
  refrigerator:          Refrigerator,
  'washing-machine':     WashingMachine,
  microwave:             Microwave,
  'air-vent':            AirVent,
  'cooking-pot':         ForkKnife,
  utensils:              ForkKnife,
  fan:                   Fan,
  blinds:                Blinds,
  droplets:              Droplets,
  lamp:                  Lamp,
  'lamp-ceiling':        LampCeiling,
  lightbulb:             Lightbulb,
  wifi:                  Lightning,
  'battery-charging':    BatteryCharging,
  shirt:                 Barbell,
  dumbbell:              Barbell,
  // ── Nature & outdoors ────────────────────────────────────────────────────

  trees:                 Tree,
  'tree-pine':           Tree,
  sun:                   Sun,
  moon:                  Moon,
  waves:                 Waves,
  flame:                 Fire,
  wind:                  Wind,
  // ── Misc UI ───────────────────────────────────────────────────────────────

  star:                  Star,
  'star-half':           StarHalf,
  heart:                 Heart,
  bookmark:              Bookmark,
  rocket:                Rocket,
  sparkles:              Sparkle,
  zap:                   Lightning,
  'party-popper':        Confetti,
  gift:                  Gift,
  circle:                Circle,
  'circle-notch':        CircleNotch,
  loader:                CircleNotch,
  'loader-2':            CircleNotch,
  box:                   Package,
  layers:                Stack,
  smartphone:            DeviceMobile,
  cpu:                   Cpu,
  'graduation-cap':      GraduationCap,
  'shopping-bag':        ShoppingBag,
  'life-buoy':           Lifebuoy,
  inbox:                 Tray,
  ticket:                Ticket,
  'ticket-plus':         TicketPlus,
  bug:                   Bug,
  history:               ClockCounterClockwise,
  timer:                 Timer,
  calendar:              Calendar,
  'calendar-check':      CalendarCheck,
  'calendar-days':       CalendarDays,
  'calendar-heart':      CalendarHeart,
  'calendar-clock':      CalendarClock,
  clock:                 Clock,
  eye:                   Eye,
  'alert-triangle':      Warning,
  hammer:                Hammer,
  gavel:                 Gavel,
  briefcase:             Briefcase,
  car:                   Car,
  'car-front':           Car,
  'concierge-bell':      Bell,
  'rectangle-vertical':  RectangleVertical,
  'folder-open':         FolderOpen,
  'folder-plus':         FolderPlus,
  'folder-x':            FolderX,
  gauge:                 Gauge,
  'alert-circle':        AlertCircle,
  'external-link':       ExternalLink,
  link:                  LinkSimple,
  'more-horizontal':     DotsThree,
  'more-vertical':       DotsThreeVertical,
  archive:               Archive,
  ban:                   Prohibit,
  'bell-off':            BellSlash,
  reply:                 ArrowBendUpLeft,
  'circle-alert':        WarningCircle,
  'cloud-off':           CloudSlash,
  // ── Help centre / documentation ────────────────────────────────────────────

  'user-circle':         UserCircle,
  'clipboard-text':      ClipboardText,
  warning:               Warning,
  sparkle:               Sparkle,
  'book-open':           BookOpenText,
  'thumbs-up':           ThumbsUp,
  'thumbs-down':         ThumbsDown,
};

export default function Icon({ name, className, ...rest }) {
  const Cmp = MAP[name] || House;
  return <Cmp className={className} {...rest} />;
}
