import { test, expect } from '@playwright/test';
import { ADMIN, SEEKER, seed } from '../../../helpers/app.js';

/* Help centre.
 *
 * The content is compiled at build time into a virtual module, so a broken
 * frontmatter field or a renamed category does not fail the build — it fails
 * silently at runtime as an empty page or a dead link. These specs assert on the
 * rendered result rather than on the source files, which is the only place that
 * distinction shows up.
 *
 * The access model matters most: `access: staff` articles are compiled into the
 * SAME client bundle as public ones and are hidden only by a filter in
 * lib/help.js. That is a UX boundary, not a security one — but it is the
 * boundary the product currently claims, so it needs a test that would fail
 * loudly the day the filter regresses. */

const listen = (page) => {
  const errors = [];
  page.on('pageerror', (e) => errors.push(e.message));
  page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
  return errors;
};

/** Help pages render an h1; wait for it rather than for networkidle (lazy route). */
async function openHelp(page, path) {
  await page.goto(path, { waitUntil: 'domcontentloaded' });
  await expect(page.locator('h1').first()).toBeVisible({ timeout: 30_000 });
}

/* The not-found state is rendered by <EmptyState>, which uses a <p> rather than
   a heading — so an unresolved article legitimately has no h1 and specs that hit
   it must wait on this copy instead. It doubles as the staff-gating assertion:
   a filtered-out runbook resolves to nothing and lands here, which is a stronger
   signal than merely "the body did not render". */
const NOT_FOUND = /could not find that article/i;

async function openHelpNotFound(page, path) {
  await page.goto(path, { waitUntil: 'domcontentloaded' });
  await expect(page.getByText(NOT_FOUND).first()).toBeVisible({ timeout: 30_000 });
}

test.describe('Help centre — public surface', () => {
  test('landing lists the public categories and no staff runbooks', async ({ page }) => {
    const errors = listen(page);
    await seed(page, {});
    await openHelp(page, '/help');

    // A public visitor sees the consumer taxonomy.
    await expect(page.getByRole('link', { name: /Getting started/i }).first()).toBeVisible();

    // ...and never the staff section, which is the whole point of the filter.
    await expect(page.getByText(/Ops playbook/i)).toHaveCount(0);
    expect(errors).toEqual([]);
  });

  test('a category page lists its articles', async ({ page }) => {
    await seed(page, {});
    await openHelp(page, '/help/c/getting-started');

    // Every article filed under this category should be reachable from it.
    const links = page.locator('a[href*="/help/a/"]');
    expect(await links.count()).toBeGreaterThan(0);
    await expect(page.getByRole('link', { name: /What is PuneNest/i }).first()).toBeVisible();
  });

  test('an article renders compiled prose, not raw markdown', async ({ page }) => {
    const errors = listen(page);
    await seed(page, {});
    await openHelp(page, '/help/a/what-is-punenest');

    const body = page.locator('.doc-prose').first();
    await expect(body).toBeVisible();

    // Markdown that failed to compile would surface as literal syntax.
    const text = await body.innerText();
    expect(text).not.toMatch(/^#{1,6}\s/m);      // unrendered headings
    expect(text).not.toMatch(/\]\(\/help\//);     // unrendered links
    expect(errors).toEqual([]);
  });

  test('every in-page TOC anchor resolves to a real heading', async ({ page }) => {
    await seed(page, {});
    await openHelp(page, '/help/a/what-is-punenest');

    /* Heading ids are generated by slugifying the heading text. The slugifier has
       already shipped two bugs — HTML entities leaking into ids, and Devanagari
       slugging to an empty string — and both produced a TOC that silently
       scrolled nowhere. An empty or duplicated id is the signature of both. */
    const ids = await page.locator('.doc-prose :is(h2,h3)[id]').evaluateAll(
      (els) => els.map((e) => e.id),
    );
    for (const id of ids) expect(id).not.toBe('');
    expect(new Set(ids).size).toBe(ids.length);

    const targets = await page.locator('.doc-toc a[href^="#"], a.doc-toc__link[href^="#"]')
      .evaluateAll((els) => els.map((e) => e.getAttribute('href').slice(1)));
    for (const target of targets) {
      expect(ids, `TOC links to #${target} but no heading has that id`).toContain(target);
    }
  });

  test('search finds an article by a word in its title', async ({ page }) => {
    await seed(page, {});
    await openHelp(page, '/help/search?q=brokerage');

    await expect(page.getByRole('link', { name: /brokerage/i }).first()).toBeVisible();
  });

  test('search degrades to an empty state rather than an error', async ({ page }) => {
    const errors = listen(page);
    await seed(page, {});
    await openHelp(page, '/help/search?q=zzzzzznotathing');

    // The page must still render its heading — a thrown search would white-screen.
    await expect(page.locator('h1').first()).toBeVisible();
    expect(errors).toEqual([]);
  });

  test('FAQ and changelog render', async ({ page }) => {
    const errors = listen(page);
    await seed(page, {});

    await openHelp(page, '/help/faq');
    await expect(page.locator('h1').first()).toBeVisible();

    await openHelp(page, '/help/changelog');
    await expect(page.locator('h1').first()).toBeVisible();

    expect(errors).toEqual([]);
  });

  test('/docs redirects into the help centre', async ({ page }) => {
    await seed(page, {});
    await page.goto('/docs', { waitUntil: 'domcontentloaded' });
    await expect(page.locator('h1').first()).toBeVisible({ timeout: 30_000 });
    expect(new URL(page.url()).pathname).toBe('/help');
  });

  test('an unknown article slug fails soft', async ({ page }) => {
    const errors = listen(page);
    await seed(page, {});
    await openHelpNotFound(page, '/help/a/no-such-article-exists');

    // It must explain itself rather than white-screen or render an empty shell.
    await expect(page.locator('.doc-prose')).toHaveCount(0);
    expect(errors).toEqual([]);
  });
});

test.describe('Help centre — staff content boundary', () => {
  /* These two specs are a matched pair. Asserting only that staff can see the
     runbook would pass even if everyone could; asserting only that the public
     cannot would pass even if nobody could. */

  test('an anonymous visitor cannot reach a staff runbook', async ({ page }) => {
    await seed(page, {});
    // A gated article resolves to nothing, so the reader gets the same
    // not-found state as a bad slug — the runbook's existence is not disclosed.
    await openHelpNotFound(page, '/help/a/verification-sla');

    await expect(page.locator('.doc-prose')).toHaveCount(0);
    // The internal SLA copy must not be anywhere on the page.
    expect(await page.locator('body').innerText()).not.toMatch(/turnaround target/i);
  });

  test('a signed-in seeker cannot reach a staff runbook either', async ({ page }) => {
    // Role, not merely authentication, is what gates staff content.
    await seed(page, { user: SEEKER });
    await openHelpNotFound(page, '/help/a/ticket-escalation');

    await expect(page.locator('.doc-prose')).toHaveCount(0);
  });

  test('an admin can reach the same runbook', async ({ page }) => {
    await seed(page, { user: ADMIN });
    await openHelp(page, '/help/a/verification-sla');

    await expect(page.locator('.doc-prose').first()).toBeVisible();
  });

  test('the staff section appears on the landing page only for staff', async ({ page }) => {
    await seed(page, { user: ADMIN });
    await openHelp(page, '/help');

    await expect(page.getByText(/Ops playbook/i).first()).toBeVisible();
  });
});
