package com.draazy.api.catalog.property;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;

/**
 * Card projection for search/lists. Deliberately carries no owner contact — the contact gate lives
 * on the detail path — and every field here is something the grid filters or badges on.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record PropertySummary(
        String id,
        String slug,
        String title,
        String deal,
        String propertyType,
        BigDecimal bhk,
        Long price,
        String priceUnit,
        BigDecimal area,
        String areaUnit,
        String furnishing,
        String possession,
        /**
         * Permitted zoning for plots and farm land; null for anything with a building on it. On the
         * card because a facet the list payload omits is a facet the grid cannot honestly filter on.
         */
        String landUse,
        /**
         * Grid filters ({@link ListingFacets} has a predicate for each), so the card must carry them
         * or the client fabricates them. Null is meaningful: unstated, not zero and not a default.
         */
        Integer ageYears,
        Integer floor,
        Integer totalFloors,
        String facing,
        String room,
        List<String> tenants,
        String availableFrom,
        Boolean pets,
        /**
         * Legal facts about a named society, not opinions about a listing. Narrow-only filters
         * server-side, so a false is safe and a fabricated true is not.
         */
        boolean societyVerified,
        boolean conveyanceDone,
        String locality,
        String localitySlug,
        String societySlug,
        String city,
        Double lat,
        Double lng,
        String coverImage,
        int imageCount,
        boolean verified,
        boolean ownerVerified,
        boolean ownershipVerified,
        String postedByType,
        String status,
        String lifecycleTrack,
        String lifecycleStage,
        String dealStatus,
        boolean boosted,
        /**
         * Editorial promotion, distinct from the paid {@code boosted}. On the card because that is
         * where the badge renders.
         */
        boolean featured,
        /**
         * Listing completeness, 0–100, generated by the database (V94). Absent rather than zero on a
         * row not yet read back, since a card printing 0 for a complete listing is worse than blank.
         */
        Integer qualityScore,
        /**
         * Freshness tier ({@link Freshness}), derived per request so it cannot go stale. Sent
         * alongside {@code lastConfirmedAt}: the timestamp renders, the tier decides tone and order.
         */
        String freshness,
        Instant createdAt,
        /**
         * When the owner last confirmed availability (V86); null until somebody has. The
         * buyer-facing half of the freshness signal, and a claim the platform can stand behind.
         */
        Instant lastConfirmedAt) {
}
