package com.punenest.api.catalog;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.punenest.api.catalog.property.Property;
import com.punenest.api.catalog.property.PropertyRepository;
import com.punenest.api.catalog.property.PropertyStatus;
import com.punenest.api.identity.user.User;
import com.punenest.api.identity.user.UserRepository;
import com.punenest.api.support.AbstractApiTest;
import jakarta.persistence.EntityManager;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * The listings search, once it became the server's job (D26).
 *
 * <p>Every filter asserted here was previously evaluated in the browser over a fully-downloaded
 * catalogue. That arrangement had two failure modes, and this class exists to keep both closed.
 * The loud one: six of these facets had no column, so against the live API they compared against
 * {@code undefined} and returned an empty page — a filter that looks like it works and silently
 * hides the entire catalogue. The quiet one, and the worse one: a predicate the database cannot
 * see cannot take part in {@code ORDER BY} or {@code LIMIT}, so filtering after the fetch meant
 * page two was a page of the wrong set. Nothing about that is visible from a screenshot, which is
 * why it survived so long.
 *
 * <p>The score cases pin exact integers rather than ranges. A weighting is a product decision, not
 * an implementation detail: if someone reweights photos from 25 to 20, that should fail a test and
 * be argued about, not drift.
 */
@DisplayName("Listings search — filtering, scoring and ranking, in SQL")
class ListingSearchTest extends AbstractApiTest {

    @Autowired
    UserRepository users;
    @Autowired
    PropertyRepository properties;
    @Autowired
    EntityManager em;

    private User seller;

    @BeforeEach
    void seedOwner() {
        seller = new User(String.format("9%09d", System.nanoTime() % 1_000_000_000L), "owner");
        seller.setName("Search Owner");
        seller.setMobileVerified(true);
        seller = users.saveAndFlush(seller);
    }

    private Property rent(String title) {
        Property p = new Property(seller, title, "rent", "apartment", 25000L, "Kothrud", "Pune");
        p.setBhk(new BigDecimal("2"));
        p.setPriceUnit("per-month");
        p.setStatus(PropertyStatus.APPROVED);
        return p;
    }

    private Property buy(String title) {
        Property p = new Property(seller, title, "buy", "apartment", 9000000L, "Baner", "Pune");
        p.setBhk(new BigDecimal("3"));
        p.setPriceUnit("total");
        p.setStatus(PropertyStatus.APPROVED);
        return p;
    }

    /**
     * Save, then force a round-trip to the database.
     *
     * <p>Not ceremony: {@code quality_score} is a generated column, so the value only exists once
     * Postgres has computed it. The in-memory instance a save returns has {@code null} there, and a
     * test that read it back off that instance would assert nothing at all while appearing to pass.
     */
    private Property persist(Property p) {
        Property saved = properties.saveAndFlush(p);
        em.flush();
        em.clear();
        return properties.findById(saved.getId()).orElseThrow();
    }

    @Nested
    @DisplayName("quality score (V94) — generated by the database, to the point")
    class QualityScore {

        @Test
        @DisplayName("an empty listing scores zero, and is not rescued by having been posted")
        void emptyListingScoresZero() {
            assertThat(persist(rent("Bare")).getQualityScore()).isZero();
        }

        @Test
        @DisplayName("a rent listing scores each block exactly as specified")
        void rentScoreIsExact() {
            Property p = rent("Complete");
            p.setImages(List.of("a", "b", "c"));            // photos: 3+          -> 25
            p.setDescription("x".repeat(200));              // description: 200+   -> 15
            p.setOwnerVerified(true);                       // trust: owner        -> 10
            p.verifyOwnership(Instant.now(), null);         // trust: ownership    -> 10
            p.setFurnishing("furnished");                   // completeness        ->  5
            p.setFacing("east");                            //                     ->  5
            p.setFloor(3);                                  //                     ->  5
            p.setPossession("ready-to-move");               //                     ->  5
            p.setDeposit(50000L);                           //                     ->  5
            p.setAmenities(List.of("lift", "parking", "gym", "pool", "security")); // 5+ -> 15

            assertThat(persist(p).getQualityScore()).isEqualTo((short) 100);
        }

        @Test
        @DisplayName("the cover image counts as one photo when there is no gallery")
        void coverImageIsAPhoto() {
            Property p = rent("Cover only");
            p.setCoverImage("https://example.test/cover.jpg");
            // 8 for a single photo and nothing else. The browser scored `gallery` and ignored the
            // cover entirely, so a listing with exactly one usable image scored as if it had none.
            assertThat(persist(p).getQualityScore()).isEqualTo((short) 8);
        }

        @Test
        @DisplayName("unfurnished is a real answer, but a smaller one than furnished")
        void unfurnishedScoresLessThanFurnished() {
            Property bare = rent("Unfurnished");
            bare.setFurnishing("unfurnished");
            Property done = rent("Furnished");
            done.setFurnishing("furnished");

            // 3 against 5: stating "unfurnished" is information a seeker can act on, so it cannot
            // score zero; it also does not make the listing as complete as one that is furnished.
            assertThat(persist(bare).getQualityScore()).isEqualTo((short) 3);
            assertThat(persist(done).getQualityScore()).isEqualTo((short) 5);
        }

        @Test
        @DisplayName("a buy listing scores its own blocks — paperwork replaces the owner check")
        void buyScoreIsExact() {
            Property p = buy("Complete sale");
            p.setImages(List.of("a", "b", "c"));            // photos              -> 25
            p.setDescription("x".repeat(200));              // description         -> 15
            p.verifyOwnership(Instant.now(), null);         // trust: ownership    -> 10
            p.setDocsCount(3);                              // trust: 3+ documents -> 10
            p.setFurnishing("furnished");                   // completeness        ->  4
            p.setFacing("east");                            //                     ->  4
            p.setFloor(3);                                  //                     ->  4
            p.setTotalFloors(12);                           //                     ->  4
            p.setArea(new BigDecimal("1200"));              //                     ->  4
            p.setPossession("ready-to-move");               //                     ->  5
            p.setAmenities(List.of("lift", "parking", "gym", "pool", "security")); // -> 15

            assertThat(persist(p).getQualityScore()).isEqualTo((short) 100);
        }

        @Test
        @DisplayName("the score follows an edit with nothing to recompute")
        void scoreFollowsTheListing() {
            Property p = persist(rent("Growing"));
            assertThat(p.getQualityScore()).isZero();

            p.setImages(List.of("a", "b", "c"));
            // No recompute call anywhere in this test, deliberately: the entire argument for a
            // generated column over a maintained one is that there is no call to forget.
            assertThat(persist(p).getQualityScore()).isEqualTo((short) 25);
        }
    }

    @Nested
    @DisplayName("freshness — derived from the clock, so it can never be stored")
    class FreshnessTier {

        private String tierOf(Instant confirmed) throws Exception {
            Property p = rent("Freshness " + System.nanoTime());
            p.confirmAvailable(confirmed);
            Property saved = persist(p);
            return mvc.perform(get("/properties/" + saved.getId()))
                    .andExpect(status().isOk())
                    .andReturn().getResponse().getContentAsString()
                    .replaceAll("(?s).*\"freshness\"\\s*:\\s*\"([a-z]+)\".*", "$1");
        }

        @Test
        @DisplayName("each boundary lands on the tier it names")
        void boundariesAreInclusive() throws Exception {
            Instant now = Instant.now();
            assertThat(tierOf(now)).isEqualTo("active");
            assertThat(tierOf(now.minus(7, ChronoUnit.DAYS))).isEqualTo("active");
            assertThat(tierOf(now.minus(8, ChronoUnit.DAYS))).isEqualTo("aging");
            assertThat(tierOf(now.minus(14, ChronoUnit.DAYS))).isEqualTo("aging");
            assertThat(tierOf(now.minus(15, ChronoUnit.DAYS))).isEqualTo("stale");
            assertThat(tierOf(now.minus(30, ChronoUnit.DAYS))).isEqualTo("stale");
            assertThat(tierOf(now.minus(31, ChronoUnit.DAYS))).isEqualTo("dormant");
        }

        @Test
        @DisplayName("a listing nobody has confirmed falls back to when it was posted")
        void neverConfirmedFallsBackToPosting() throws Exception {
            // Posting is itself an assertion that the property is available, so a listing posted
            // today is active even though nobody has answered a nudge yet.
            assertThat(tierOf(null)).isEqualTo("active");
        }
    }

    @Nested
    @DisplayName("the facets that had no column (V95)")
    class NewFacets {

        private long count(String query) throws Exception {
            String body = mvc.perform(get("/properties?" + query))
                    .andExpect(status().isOk())
                    .andReturn().getResponse().getContentAsString();
            return Long.parseLong(body.replaceAll("(?s).*\"totalElements\"\\s*:\\s*(\\d+).*", "$1"));
        }

        @Test
        @DisplayName("an owner who stated no tenant preference matches no tenant filter")
        void emptyTenantsMatchesNoFilter() throws Exception {
            Property silent = rent("No preference stated");
            Property picky = rent("Family only");
            picky.setTenants(List.of("family"));
            Property other = rent("Company only");
            other.setTenants(List.of("company"));
            persist(silent);
            persist(picky);
            persist(other);

            // Each filter returns only the owner who said that word, and the silent listing is in
            // neither. "Unknown" is not a value a filter can match -- admitting it would put an
            // owner who never answered in front of a seeker who asked a specific question, which
            // is the same fabrication as defaulting the field to a guess.
            assertThat(count("tenants=family&owner=" + seller.getId())).isEqualTo(1);
            assertThat(count("tenants=company&owner=" + seller.getId())).isEqualTo(1);
        }

        @Test
        @DisplayName("the move-in filter is cumulative — a month also takes what is free today")
        void availableFromIsCumulative() throws Exception {
            Property now = rent("Free today");
            now.setAvailableFrom("now");
            Property fortnight = rent("Free in a fortnight");
            fortnight.setAvailableFrom("15");
            Property month = rent("Free in a month");
            month.setAvailableFrom("30");
            persist(now);
            persist(fortnight);
            persist(month);

            String owner = "&owner=" + seller.getId();
            assertThat(count("availableFrom=now" + owner)).isEqualTo(1);
            assertThat(count("availableFrom=15" + owner)).isEqualTo(2);
            assertThat(count("availableFrom=30" + owner)).isEqualTo(3);
        }

        @Test
        @DisplayName("an unknown move-in bucket matches nothing rather than everything")
        void unknownBucketMatchesNothing() throws Exception {
            persist(rent("Anything"));
            // Answering an unrecognised value with the whole catalogue is the failure that looks
            // most like success.
            assertThat(count("availableFrom=whenever&owner=" + seller.getId())).isZero();
        }

        @Test
        @DisplayName("a facet whose every token is rejected returns nothing, not everything")
        void unsanitisableTokensMatchNothing() throws Exception {
            persist(rent("Ordinary"));

            // The tokens below cannot be slugs, so they are dropped before they reach SQL. The
            // trap is what happens next: an empty token list looks exactly like an unused facet,
            // and treating them alike hands back the whole catalogue as the answer to a filter
            // nobody could have matched. An empty page is legible; a full one is a lie.
            String owner = "&owner=" + seller.getId();
            assertThat(count("localities=%27%20or%201%3D1--" + owner)).isZero();
            // `%3Cscript%3E` is normalised away by the web layer before model binding, which turns
            // this from "invalid token" into "facet absent" and makes the assertion vacuous.
            // Keep the check on a token shape that reaches ListingFacets and is rejected there.
            assertThat(count("amenities=%27%20or%201%3D1--" + owner)).isZero();
            assertThat(count("tenants=%27%20or%201%3D1--" + owner)).isZero();
        }

        @Test
        @DisplayName("a listing that never stated its age is not treated as brand new")
        void unstatedAgeIsNotZero() throws Exception {
            Property silent = rent("Age unstated");
            Property known = rent("Five years old");
            known.setAgeYears(5);
            persist(silent);
            persist(known);

            String owner = "&owner=" + seller.getId();
            assertThat(count("minAge=0&maxAge=10" + owner)).isEqualTo(1);
            assertThat(count("maxAge=3" + owner)).isZero();
        }

        @Test
        @DisplayName("occupancy, room shape, zoning and pets each narrow on their own column")
        void remainingFacetsNarrow() throws Exception {
            Property pg = rent("PG with doubles");
            pg.setSharing(List.of("double", "triple"));
            pg.setRoom("shared");
            pg.setPets(true);
            Property plot = buy("Farm plot");
            plot.setLandUse("agricultural");
            persist(pg);
            persist(plot);

            String owner = "&owner=" + seller.getId();
            assertThat(count("sharing=double" + owner)).isEqualTo(1);
            assertThat(count("sharing=five" + owner)).isZero();
            assertThat(count("room=shared" + owner)).isEqualTo(1);
            assertThat(count("pets=true" + owner)).isEqualTo(1);
            assertThat(count("landUse=agricultural" + owner)).isEqualTo(1);
            // `pets=false` is "I did not ask", not "show me the ones that forbid pets".
            assertThat(count("pets=false" + owner)).isEqualTo(2);
        }

        @Test
        @DisplayName("amenities AND — two ticks are two requirements, not two alternatives")
        void amenitiesAreConjunctive() throws Exception {
            Property both = rent("Lift and parking");
            both.setAmenities(List.of("lift", "parking"));
            Property one = rent("Lift only");
            one.setAmenities(List.of("lift"));
            persist(both);
            persist(one);

            String owner = "&owner=" + seller.getId();
            assertThat(count("amenities=lift" + owner)).isEqualTo(2);
            assertThat(count("amenities=lift,parking" + owner)).isEqualTo(1);
        }

        @Test
        @DisplayName("a BHK chip may be an open top — 3plus does not hide the 4BHKs")
        void bhkPlusIsARange() throws Exception {
            Property two = rent("Two bed");
            Property four = rent("Four bed");
            four.setBhk(new BigDecimal("4"));
            persist(two);
            persist(four);

            String owner = "&owner=" + seller.getId();
            assertThat(count("bhks=2" + owner)).isEqualTo(1);
            assertThat(count("bhks=3plus" + owner)).isEqualTo(1);
            assertThat(count("bhks=2,3plus" + owner)).isEqualTo(2);
        }
    }

    @Nested
    @DisplayName("near a point — a circle, without PostGIS")
    class NearPoint {

        private long count(String query) throws Exception {
            String body = mvc.perform(get("/properties?" + query))
                    .andExpect(status().isOk())
                    .andReturn().getResponse().getContentAsString();
            return Long.parseLong(body.replaceAll("(?s).*\"totalElements\"\\s*:\\s*(\\d+).*", "$1"));
        }

        @Test
        @DisplayName("the radius is a circle, not the box used to find it")
        void cornersAreTrimmed() throws Exception {
            // Pune centre.
            double lat = 18.5204;
            double lng = 73.8567;

            Property near = rent("Two km north");
            near.setLat(lat + 0.018);
            near.setLng(lng);

            // ~4km north AND ~4km east: inside a 5km bounding box on both axes, but ~5.7km away on
            // the diagonal. This is the listing a box-only implementation wrongly returns.
            Property corner = rent("On the diagonal");
            corner.setLat(lat + 0.036);
            corner.setLng(lng + 0.038);

            persist(near);
            persist(corner);

            String owner = "&owner=" + seller.getId();
            assertThat(count("nearLat=" + lat + "&nearLng=" + lng + "&nearRadiusKm=5" + owner))
                    .isEqualTo(1);
            assertThat(count("nearLat=" + lat + "&nearLng=" + lng + "&nearRadiusKm=10" + owner))
                    .isEqualTo(2);
        }

        @Test
        @DisplayName("a centre without a radius is an incomplete question, and is ignored")
        void incompleteNearPointIsIgnored() throws Exception {
            Property anywhere = rent("Somewhere");
            anywhere.setLat(18.52);
            anywhere.setLng(73.85);
            persist(anywhere);

            assertThat(count("nearLat=18.52&owner=" + seller.getId())).isEqualTo(1);
        }

        @Test
        @DisplayName("an absurd radius is clamped, not honoured — and not rejected either")
        void radiusIsClamped() throws Exception {
            Property pune = rent("In Pune");
            pune.setLat(18.5204);
            pune.setLng(73.8567);
            Property faraway = rent("In Delhi");
            faraway.setLat(28.6139);
            faraway.setLng(77.2090);
            persist(pune);
            persist(faraway);

            // 20,000km would otherwise size a bounding box spanning the planet, on an endpoint
            // anybody can call without signing in. Clamped to 50km, Delhi stays out.
            String owner = "&owner=" + seller.getId();
            assertThat(count("nearLat=18.5204&nearLng=73.8567&nearRadiusKm=20000" + owner))
                    .isEqualTo(1);
        }
    }

    @Nested
    @DisplayName("ranking — merit by default, and never over a buyer's own choice")
    class Ranking {

        private List<String> titles(String query) throws Exception {
            String body = mvc.perform(get("/properties?" + query))
                    .andExpect(status().isOk())
                    .andReturn().getResponse().getContentAsString();
            return java.util.regex.Pattern.compile("\"title\"\\s*:\\s*\"([^\"]+)\"")
                    .matcher(body).results().map(m -> m.group(1)).toList();
        }

        @Test
        @DisplayName("featured outranks every verification put together")
        void featuredDominates() throws Exception {
            Property plain = rent("Featured but plain");
            plain.setFeatured(true);
            Property decorated = rent("Verified and complete");
            decorated.setOwnerVerified(true);
            decorated.verifyOwnership(Instant.now(), null);
            decorated.setReraId("P52100012345");
            decorated.setImages(List.of("a", "b", "c"));
            persist(plain);
            persist(decorated);

            // 1000 beats 250 + 200 + 80 + freshness + score, and is spaced to do so on purpose:
            // an editorial decision is not something a complete listing can out-accumulate.
            assertThat(titles("owner=" + seller.getId())).containsExactly(
                    "Featured but plain", "Verified and complete");
        }

        @Test
        @DisplayName("between equals, the more complete listing wins")
        void qualityBreaksTheTie() throws Exception {
            Property sparse = rent("Sparse");
            Property rich = rent("Rich");
            rich.setImages(List.of("a", "b", "c"));
            rich.setDescription("x".repeat(200));
            persist(sparse);
            persist(rich);

            assertThat(titles("owner=" + seller.getId())).containsExactly("Rich", "Sparse");
        }

        @Test
        @DisplayName("an explicit price sort is honoured — merit does not outrank the buyer")
        void explicitSortWins() throws Exception {
            Property dear = rent("Dear and featured");
            dear.setPrice(90000L);
            dear.setFeatured(true);
            Property cheap = rent("Cheap and plain");
            cheap.setPrice(5000L);
            persist(dear);
            persist(cheap);

            // The same rule D59 already applied to paid placement, extended to merit: a control
            // that silently does something other than what it says is worse than no control.
            assertThat(titles("owner=" + seller.getId() + "&sort=price,asc"))
                    .containsExactly("Cheap and plain", "Dear and featured");
        }

        @Test
        @DisplayName("rank=newest orders by recency, and does not re-sort by merit")
        void newestIgnoresMerit() throws Exception {
            Property older = rent("Older but excellent");
            older.setImages(List.of("a", "b", "c"));
            older.setDescription("x".repeat(200));
            persist(older);
            Property newer = rent("Newer and bare");
            persist(newer);

            // A buyer who asked for the newest listings and was shown the best-scoring ones has
            // been given something other than what the control names.
            assertThat(titles("owner=" + seller.getId() + "&rank=newest").getFirst())
                    .isEqualTo("Newer and bare");
        }
    }

    @Nested
    @DisplayName("the public floor still holds under every new facet")
    class VisibilityFloor {

        @Test
        @DisplayName("a pending listing cannot be reached by any of the new filters")
        void newFacetsDoNotBypassTheFloor() throws Exception {
            Property hidden = rent("Awaiting moderation");
            hidden.setStatus(PropertyStatus.PENDING);
            hidden.setPets(true);
            hidden.setTenants(List.of("family"));
            hidden.setSharing(List.of("double"));
            persist(hidden);

            // Each new predicate is ANDed into the same specification that pins the floor, so this
            // asserts the composition rather than any one filter: a facet added to the wrong
            // builder would surface unapproved rows anonymously.
            String owner = "&owner=" + seller.getId();
            mvc.perform(get("/properties?pets=true" + owner))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.totalElements").value(0));
            mvc.perform(get("/properties?tenants=family" + owner))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.totalElements").value(0));
            mvc.perform(get("/properties?sharing=double" + owner))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.totalElements").value(0));
        }
    }
}
