
/** Route pattern to display name. Kept client-side so a rename never relabels stored history; an unmapped
 * pattern renders as its raw path so a gap is visibly unfinished. */
const PAGE_LABELS = {
  '/': 'Home',
  '/listings': 'Listings',
  '/property/:id': 'Property detail',
  '/flatmates': 'Flatmates',
  '/list-property': 'Post property',
  '/services': 'Services',
  '/locality': 'Locality guides',
  '/locality/:slug': 'Locality detail',
  '/society/:slug': 'Society detail',
  '/emi-calculator': 'EMI calculator',
  '/home-loans': 'Home loans',
  '/map': 'Map search',
  '/compare': 'Compare',
  '/plans': 'Plans & pricing',
  '/dashboard': 'Dashboard',
  '/owner-hub': 'Owner hub',
  '/owner-hub/property/:id': 'Owner hub — property',
  '/owner/:id': 'Owner profile',
  '/pay-rent': 'Pay rent',
  '/checkout': 'Checkout',
  '/messages': 'Messages',
  '/notifications': 'Notifications',
  '/saved': 'Saved',
  '/search': 'Search',
  '/support': 'Support',
  '/contact': 'Contact',
  '/help': 'Help centre',
  '/help/faq': 'Help — FAQ',
  '/help/search': 'Help — search',
  '/help/a/:slug': 'Help — article',
  '/help/c/:categoryId': 'Help — category',
  '/help-center': 'Help centre (legacy)',
  '/privacy': 'Privacy policy',
  '/disclaimer': 'Disclaimer',
  '/docs': 'Documents',
  '/*': 'Not found (404)',
};

export const pageLabel = (path) => PAGE_LABELS[path] || path;
