-- V43 — the unpaid-order cap, enforced by the database (D153).
--
-- WHAT WAS WRONG
-- --------------
-- `ServiceRequestService.create` counts the caller's open `awaiting-payment` rows for a desk and
-- then inserts one. Between the count and the insert there is nothing: the transaction runs at
-- READ COMMITTED, the count takes no lock, and the endpoint has no throttle in front of it (D2).
-- N concurrent POSTs therefore all read zero, all insert, and all open a real Cashfree order --
-- which is precisely the unbounded-orders outcome the cap was added to prevent. The check held
-- against the accident it was written for (a double click, a page reload) and failed against the
-- attack, and only one of those two is why the cap exists.
--
-- A count-then-insert cannot be fixed by moving the count: any read-then-write over rows that do
-- not exist yet has this hole, because there is no row to lock. What closes it is a uniqueness
-- constraint, which the database evaluates at write time and which two concurrent writers cannot
-- both satisfy -- the second blocks on the first's index entry and is refused when it commits.
--
-- WHY THIS SHAPE
-- --------------
-- Partial, on (requester_id, type) WHERE status = 'awaiting-payment', because the invariant is
-- exactly "one unpaid order per person per desk" and nothing wider. Once a request is paid for
-- (`new`), cancelled, or completed it leaves the index entirely, so a customer may raise as many
-- rent agreements over time as they like -- the cap is on *outstanding* orders, not on volume, and
-- not a rate limit. It mirrors `uq_service_requests_payment_ref` from V39, which is partial for the
-- same reason: the rows outside the predicate are not in conflict with anything.
--
-- The unique index is a backstop, not the user-facing rule. The count in `create` stays as the fast
-- path because it produces the better message on the ordinary double click, and the service now
-- translates this constraint's violation into the same 409 with the same text, so the API contract
-- does not change -- a caller cannot tell which of the two refused them, and should not need to.
--
-- The index matches MAX_OPEN_UNPAID_PER_TYPE = 1 exactly. If that constant is ever raised, this
-- index must be replaced (a unique index cannot express "at most N"); the constant's javadoc says
-- so, because the failure mode otherwise is the service allowing a second order that the database
-- then refuses with a message about the first.
--
-- BACKFILL
-- --------
-- None is written. `awaiting-payment` only exists from V39, is left by the payment webhook within
-- the life of a checkout, and the count-based cap has been in front of the endpoint since; a
-- pre-existing duplicate pair would be a row that was already a defect. Should one exist, this
-- CREATE INDEX fails loudly at deploy time with the offending pair named -- which is the right
-- outcome, because silently choosing which of two live gateway orders to disown is not a decision a
-- migration may make.

CREATE UNIQUE INDEX uq_service_requests_open_unpaid
    ON service_requests (requester_id, type)
    WHERE status = 'awaiting-payment';
