-- V54 drops an index nothing can use, and corrects a comment that has been describing the opposite
-- of the code since V27. Closes debt D176, which is two findings from one sweep and has no single
-- theme beyond "the database is telling a lie and the next reader will believe it".
--
-- =========================================================================================
-- 1. `idx_transactions_owner` is dead. Not "unused on this box" -- unusable.
-- =========================================================================================
--
-- V6 created `(owner_id, date)` alongside `(property_id, date)` on the assumption that an owner's
-- ledger would be read by owner. It never was. The finance surface is mounted at
-- `/me/finances/{propId}/...`: `FinanceService` resolves ownership once, through `properties`
-- (`findByIdAndOwner_Id`), and every read after that is scoped to the property alone. V12 rebuilt
-- both indexes as partial ones and carried the owner index across unexamined; V51 replaced the
-- property index with a covering one and explicitly left this one alone, deferring the question.
-- This is that question answered.
--
-- THE ARGUMENT THAT SETTLES IT: no query shape exists that could choose it.
--
-- `TransactionRepository` is the only door to this table -- there is no native SQL against
-- `transactions` anywhere in the application (`AdminMetricsRepository`, which holds every hand-
-- written query on the platform, does not mention it), and no seed writes it. Its five statements
-- are, in full:
--
--   findLiveByPropertyId          property_id = ? and archived = false, order by date desc
--   (its countQuery)              property_id = ? and archived = false
--   findLiveByIdAndPropertyId     id = ? and property_id = ? and archived = false
--   findLiveRecurringByPropertyId property_id = ? and archived = false and recurring <> 'none'
--   sumByTypeSince                property_id = ? and archived = false [and date >= ?]
--   monthlyTotalsBetween          property_id = ? and archived = false and date >= ? and date < ?
--
-- Every one of them leads on `property_id`. `owner_id` is the leading column of this index, so it
-- can only be reached by a predicate on `owner_id` -- a scan of a b-tree whose first key is not
-- constrained is a full index scan, which is never cheaper than the property index it would be
-- competing with here. There is no such predicate, and there cannot accidentally become one: the
-- controller has already proved ownership before any of these run, so re-filtering on `owner_id`
-- would be a second, weaker check, and `TransactionRepository`'s own contract note says reads are
-- scoped by property deliberately, so that a listing whose basis was recorded under a different
-- owner id still returns a complete ledger.
--
-- The column is not dead and is NOT dropped. `Transaction.ownerId` is the ledger row's *author* --
-- who recorded it, which is not the same fact as who owns the listing today, and is what stops a
-- new owner inheriting the previous owner's private expense history when a flat changes hands. It
-- is written on insert and read back only as part of a whole row. `Transaction.getOwnerId()` has no
-- caller anywhere in the codebase; that is the direct proof that nothing filters, sorts or groups on
-- it, which is the only thing an index on it could serve.
--
-- SUPPORTING, NOT LOAD-BEARING: `pg_stat_user_indexes` on the local test database, which has run
-- the finance suite, reports 163 scans on `idx_transactions_property_agg`, 40 on
-- `transactions_pkey` and 0 on `idx_transactions_owner`. A zero on a developer box proves nothing on
-- its own -- an unexercised index and an unusable one look identical. It is worth recording only
-- because the *other* indexes on the same table are non-zero, so this is a zero next to a control
-- rather than a quiet database. The argument above is what decides it.
--
-- WHAT THE DROP BUYS: every insert into this table maintains one fewer b-tree, as does every update
-- and every soft-delete (which flips `archived` and therefore moves the row out of the partial
-- index, a delete from the index's point of view). A ledger is append-heavy and never culled --
-- rent, maintenance and recurring expenses arrive on a schedule for as long as the owner holds the
-- flat -- so this is a cost paid forever for a plan that is never chosen.
--
-- REVERSING IT is one line, if a by-owner read is ever genuinely wanted:
--   CREATE INDEX idx_transactions_owner ON transactions (owner_id, date) WHERE archived = false;
-- Adding it back beside a query that needs it is cheaper than keeping it against one that might.
DROP INDEX idx_transactions_owner;

-- =========================================================================================
-- 2. V27's comment on `uq_flatmate_requests_target_requester` is false, and has been since it
--    shipped. The correction goes here because V27 cannot be edited.
-- =========================================================================================
--
-- V27 says, above the index:
--
--     "One request per person per target. This is what makes the interest endpoints idempotent and
--      is the reason the service does not check-then-insert: two concurrent presses would both pass
--      a check and only this can refuse the second."
--
-- Three claims, and the first two are the wrong way round from the code they sit beside.
--
--   * "idempotent" -- it is not. A second ask is REFUSED: both write paths throw
--     `alreadyInterested()` and the caller gets the contract's 409. An idempotent endpoint would
--     answer with the first request; this one declines to make a second. Refusal and idempotence
--     are different promises and a reader who believes the wrong one will write a client that
--     treats 409 as a bug.
--
--   * "the reason the service does not check-then-insert" -- the service does exactly
--     check-then-insert, in both doors, and always has.
--     `FlatmateSeekerService.express` and `FlatmateSupplyService.record` each call
--     `findByKindAndTargetIdAndRequesterId(...).isPresent()` and throw before reaching
--     `saveAndFlush`. D175 did not add that check; it moved the read to *after*
--     `locks.holdUntilCommit(FLATMATE_INTEREST, requesterId)`, because reading before the lock was
--     a stale read by construction and was answering 201 to the press that arrived a millisecond
--     late.
--
--   * "two concurrent presses would both pass a check and only this can refuse the second" -- true
--     when written, and now only the residual case. The advisory lock serialises the two presses on
--     the requester, so under READ COMMITTED the loser's post-lock read takes a fresh snapshot and
--     sees the winner's committed row. The index is the BACKSTOP for the case the lock cannot cover
--     -- an isolation level above READ COMMITTED, where the loser carries its pre-lock snapshot past
--     the check -- and the `DataIntegrityViolationException` catch beside each save turns that into
--     the same 409 rather than a 500.
--
-- So the index is right, the constraint is right, and the prose beside it argues for the opposite
-- design. That is worse than no comment: a correct constraint defends itself, whereas a wrong
-- explanation gets trusted and then propagated.
--
-- WHY V27 IS NOT EDITED IN PLACE. `spring.flyway.validate-on-migrate` is not set anywhere in this
-- repo, so Flyway's default applies and validation is ON. Editing an applied migration -- even
-- prose, even a comment -- moves its checksum, and both databases have V27 applied: `punenest`
-- (the seeded dev database) and `punenest_test`. Every subsequent boot of either would fail
-- validation, and the only ways out are `flyway repair` or rebuilding the database from empty. The
-- dev database carries hand-made local state and the register itself says to do this "when the test
-- DB is next rebuilt, never mid-wave". This is mid-wave. So the correction is recorded twice in
-- places that cost nothing to change:
--
--   * here, in the migration whose header the next person reading the history will reach, and
--   * on the index itself, below, so `\d+ flatmate_requests` carries the truth in the database
--     rather than only in a file, and
--   * as a javadoc paragraph on `FlatmateRequestRepository.findByKindAndTargetIdAndRequesterId`,
--     which is the Java side of the same invariant and the place a reader of the service lands.
--
-- If V27's text is ever corrected for real, delete this section rather than leaving two accounts.
comment on index uq_flatmate_requests_target_requester is
    'One request per (kind, target, requester). CORRECTION TO V27''s COMMENT (D176): V27 calls this '
    'the reason the service does not check-then-insert, and calls the interest endpoints '
    'idempotent. Both are false. Both write paths -- FlatmateSeekerService.express and '
    'FlatmateSupplyService.record -- do check-then-insert, and a second ask is refused with 409, '
    'not answered idempotently. Since D175 the check runs behind an advisory lock on the requester, '
    'which closes the race under READ COMMITTED; this index is the backstop for a higher isolation '
    'level, and the DataIntegrityViolationException catch beside each save turns it into the same '
    '409 rather than a 500.';
