-- V85 — index tickets by the number that raised them, newest first.
--
-- Why: D4 opens POST /service-waitlist to callers with no account, and the only thing standing
-- between the ops board and a script is a per-mobile budget — "at most N tickets from this number
-- in the last hour" — which TicketService.joinWaitlist answers with a count over exactly these two
-- columns. Without an index that count is a sequential scan of tickets, on an unauthenticated path,
-- once per request: the rate limiter would be the cheapest denial of service on the platform, and
-- it would get slower the more successfully it was attacked. The same index also serves the
-- duplicate check on (mobile, subject, status), which leads with mobile.
--
-- Why DESC on created_at: the budget query is "created_at > now() - 1 hour", a range on the second
-- column after an equality on the first, and the matching rows are the newest ones. Postgres can
-- read either direction, so this is a small ordering convenience rather than a correctness matter —
-- it matches idx_society_leads_mobile_created (V24), which exists for the identical query on the
-- identical shape of problem, and two indexes serving the same purpose should not look different.
--
-- Not unique, and not partial. Unique is plainly wrong — a number raising several tickets is the
-- normal case. Partial (WHERE mobile is not null) was tempted: most tickets today come from
-- authenticated flows and carry a mobile anyway, and the column is nullable only because V7 allowed
-- ops to raise a ticket for a guest. The saving would be near nothing on a table this shape, and a
-- partial index is a footgun for the next person writing a query that does not repeat the predicate.
create index if not exists idx_tickets_mobile_created
    on public.tickets (mobile, created_at desc);
