/* Downloads the web fonts Google Fonts would have served, and emits the
 * @font-face CSS that points at the local copies.
 *
 * Why self-host at all: the <link> to fonts.googleapis.com sat on the critical
 * path and cost a full third-party round trip before a single glyph could be
 * requested — DNS + TLS + CSS, and only then the font itself. `preconnect` warms
 * the socket but cannot remove the hop. On a 4G phone, which is ~80% of this
 * audience, that is the single largest render-blocking item on the page.
 *
 * Why a script instead of pasted URLs: the woff2 filenames are content-hashed and
 * Google rotates them. Pasting them into index.html means they silently rot; this
 * can be re-run to refresh.
 *
 * The per-subset unicode-range is preserved verbatim, which is the part that
 * matters for size: an English visitor never downloads the Devanagari subsets,
 * exactly as before.
 *
 * Usage:  node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const SPEC = 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700;800&family=Noto+Sans+Devanagari:wght@400;500;600;700&display=swap';

// Google serves woff2 + unicode-range only to browsers it recognises; a bare
// fetch gets the legacy ttf payload instead.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const here = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(here, '..', 'public', 'fonts');
const cssOut = path.join(here, '..', 'src', 'styles', 'fonts.css');

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const field = (block, name) => {
  const m = block.match(new RegExp(`${name}:\\s*([^;]+);`));
  return m ? m[1].trim() : null;
};

const main = async () => {
  const res = await fetch(SPEC, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Google Fonts returned ${res.status}`);
  const css = await res.text();

  const blocks = css.split('@font-face').slice(1);
  if (!blocks.length) throw new Error('No @font-face blocks in the response');

  await mkdir(outDir, { recursive: true });

  const seen = new Map();
  const rules = [];
  let bytes = 0;

  for (const block of blocks) {
    const family = (field(block, 'font-family') || '').replace(/['"]/g, '');
    const weight = field(block, 'font-weight') || '400';
    const style = field(block, 'font-style') || 'normal';
    const range = field(block, 'unicode-range');
    const url = (block.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
    if (!family || !url) continue;

    // One family+weight spans several subsets; number them so filenames are stable
    // and human-readable rather than carrying Google's rotating hash.
    const key = `${slug(family)}-${weight}`;
    const n = (seen.get(key) || 0) + 1;
    seen.set(key, n);
    const file = `${key}-${n}.woff2`;

    const bin = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!bin.ok) throw new Error(`Font download failed (${bin.status}) for ${url}`);
    const buf = Buffer.from(await bin.arrayBuffer());
    await writeFile(path.join(outDir, file), buf);
    bytes += buf.length;

    rules.push(
      [
        '@font-face {',
        `  font-family: '${family}';`,
        `  font-style: ${style};`,
        `  font-weight: ${weight};`,
        // swap: show fallback text immediately rather than holding the paint. A
        // property listing is readable in a system font; a blank screen is not.
        '  font-display: swap;',
        `  src: url('/fonts/${file}') format('woff2');`,
        range ? `  unicode-range: ${range};` : null,
        '}',
      ].filter(Boolean).join('\n'),
    );
  }

  const header = [
    '/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.',
    ' *',
    ' * Self-hosted so the first paint does not wait on a third-party round trip.',
    ' * Re-run the script to refresh; the unicode-range split is Google\'s own, which',
    ' * is what keeps an English visitor from downloading the Devanagari subsets. */',
    '',
  ].join('\n');

  await writeFile(cssOut, `${header}${rules.join('\n\n')}\n`);
  console.log(`Wrote ${rules.length} @font-face rules, ${(bytes / 1024).toFixed(1)} KB of woff2 into public/fonts/`);
};

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
