import { localityNames, localityCoordMap } from '../../../data/localities.js';

// Locality identity is owned by the canonical registry (data/localities.js);
// derive the share-flat list + coord map from it so there is one source of truth.
const LOCALITIES = localityNames();
const TAGS = ['Vegetarian', 'Non-veg ok', 'Non-smoker', 'Early riser', 'Night owl', 'Pet-friendly', 'Working professional', 'Student', 'Fitness'];
const MOVE_LBL = { now: 'Immediately', 15: 'Within 15 days', 30: 'Within a month', 60: 'In 1–2 months' };
const FLAT_PREF_LBL = { any: 'Anyone', women: 'Women only', men: 'Men only' };
const ROOM_PREF_LBL = { any: 'No preference', private: 'Private room', shared: 'Shared room' };
const MOVE_RANK = { now: 0, 15: 15, 30: 30, 60: 60 };
const LOCALITY_COORDS = localityCoordMap();
const ROOM_IMGS = ['https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=600&q=80', 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=80', 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80', 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=600&q=80', 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80'];

const SEEKERS = [
  { id: 's1', name: 'Riya', gender: 'female', age: 24, occupation: 'UX Designer', budget: 16000, localities: ['Baner', 'Balewadi'], moveIn: 'now', flatPref: 'women', roomPref: 'private', tags: ['Vegetarian', 'Non-smoker', 'Working professional'], note: 'Looking for one more working woman to share a 2BHK in Baner. Clean, quiet, no smoking.', verified: true, time: '2 hours ago' },
  { id: 's2', name: 'Sneha', gender: 'female', age: 26, occupation: 'Data Analyst', budget: 18000, localities: ['Hinjawadi', 'Wakad'], moveIn: '15', flatPref: 'women', roomPref: 'private', tags: ['Non-smoker', 'Early riser', 'Fitness'], note: 'WFO at Hinjawadi. Want a 2BHK split with a like-minded girl. Gym buddy a bonus!', verified: true, time: '5 hours ago' },
  { id: 's3', name: 'Aditya', gender: 'male', age: 27, occupation: 'Backend Engineer', budget: 20000, localities: ['Kharadi', 'Viman Nagar'], moveIn: '30', flatPref: 'men', roomPref: 'private', tags: ['Non-veg ok', 'Night owl', 'Working professional'], note: 'Two of us looking for a third for a 3BHK near EON IT Park. Chill, respectful crowd.', verified: false, time: '1 day ago' },
  { id: 's4', name: 'Meera', gender: 'female', age: 23, occupation: 'PG Medical Student', budget: 12000, localities: ['Kothrud', 'Aundh'], moveIn: 'now', flatPref: 'women', roomPref: 'shared', tags: ['Vegetarian', 'Student', 'Early riser'], note: 'Student looking for another girl to share a 1BHK/2BHK near Kothrud. Budget-friendly.', verified: true, time: '1 day ago' },
  { id: 's5', name: 'Karan', gender: 'male', age: 29, occupation: 'Product Manager', budget: 25000, localities: ['Koregaon Park', 'Kalyani Nagar'], moveIn: '30', flatPref: 'any', roomPref: 'private', tags: ['Non-veg ok', 'Fitness', 'Pet-friendly'], note: 'Want to split a premium 2BHK in KP/Kalyani Nagar. Have a friendly dog.', verified: true, time: '2 days ago' },
  { id: 's6', name: 'Pooja', gender: 'female', age: 25, occupation: 'Marketing Lead', budget: 17000, localities: ['Wakad', 'Baner'], moveIn: '15', tags: ['Non-smoker', 'Working professional', 'Night owl'], note: 'Relocating to Pune. Need a 2BHK flatmate (woman). Easy-going, tidy.', verified: false, time: '3 days ago' },
  { id: 's7', name: 'Rahul', gender: 'male', age: 24, occupation: 'QA Engineer', budget: 14000, localities: ['Hinjawadi', 'Hadapsar'], moveIn: '60', tags: ['Vegetarian', 'Non-smoker', 'Student'], note: 'Fresh grad, looking to share a 2BHK to keep rent low. Open to Hinjawadi/Hadapsar.', verified: false, time: '4 days ago' },
  { id: 's8', name: 'Ananya', gender: 'female', age: 28, occupation: 'Architect', budget: 22000, localities: ['Aundh', 'Baner'], moveIn: '30', tags: ['Vegetarian', 'Fitness', 'Pet-friendly'], note: 'Looking for a long-term flatmate (woman) for a nice 2BHK in Aundh. Plants & cats welcome.', verified: true, time: '5 days ago' },
];
const SEED_ROOMS = [
  { id: 'rm1', society: 'Skyline Heights', localities: ['Baner'], flatType: '2 BHK', roomType: 'Private room', furnishing: 'Semi-Furnished', attachedBath: 'attached', homeTypeLabel: 'Flat', budget: 14000, deposit: 28000, moveIn: 'now', gender: 'female', food: 'veg', tags: ['Non-smoker', 'Working professional', 'Vegetarian'], note: 'One furnished private room with attached bathroom in a 2BHK. Society has gym & 24x7 security. Looking for a working woman, veg preferred.', img: ROOM_IMGS[0], verified: true, time: '2 hours ago' },
  { id: 'rm2', society: 'Lodha Belmondo', localities: ['Hinjawadi'], flatType: '3 BHK', roomType: 'Private room', furnishing: 'Furnished', attachedBath: 'shared', homeTypeLabel: 'Flat', budget: 16000, deposit: 32000, moveIn: '15', gender: 'male', food: 'any', tags: ['Non-veg ok', 'Working professional', 'Fitness'], note: 'Spare room in a fully furnished 3BHK near Phase 1. Two working guys already here, chill crowd.', img: ROOM_IMGS[1], verified: true, time: '7 hours ago' },
  { id: 'rm3', society: 'Gera World of Joy', localities: ['Kharadi'], flatType: '2 BHK', roomType: 'Shared room', furnishing: 'Semi-Furnished', attachedBath: 'shared', homeTypeLabel: 'Flat', budget: 9000, deposit: 18000, moveIn: '30', gender: 'any', food: 'any', tags: ['Student', 'Non-smoker'], note: 'Shared room (twin sharing) in a 2BHK near EON IT Park. Budget-friendly, walkable to work.', img: ROOM_IMGS[2], verified: false, time: '1 day ago' },
  { id: 'rm4', society: 'Rohan Iris', localities: ['Wakad'], flatType: '2 BHK', roomType: 'Private room', furnishing: 'Furnished', attachedBath: 'attached', homeTypeLabel: 'Flat', budget: 15000, deposit: 30000, moveIn: 'now', gender: 'female', food: 'veg', tags: ['Vegetarian', 'Early riser', 'Pet-friendly'], note: 'Bright private room with attached bathroom and balcony. Quiet, family-friendly society. Cat-friendly home.', img: ROOM_IMGS[3], verified: true, time: '2 days ago' },
  { id: 'rm5', society: 'Kumar Princeville', localities: ['Viman Nagar'], flatType: '3 BHK', roomType: 'Private room', furnishing: 'Semi-Furnished', attachedBath: 'shared', homeTypeLabel: 'Flat', budget: 18000, deposit: 36000, moveIn: '15', gender: 'any', food: 'nonveg', tags: ['Non-veg ok', 'Night owl', 'Working professional'], note: 'Premium 3BHK near Phoenix Mall, one room free. Great for IT/aviation folks.', img: ROOM_IMGS[4], verified: false, time: '4 days ago' },
  { id: 'rm6', society: 'Green Meadows Bungalow', localities: ['Kothrud'], flatType: '3 BHK', roomType: 'Private room', furnishing: 'Furnished', attachedBath: 'attached', homeTypeLabel: 'Independent House', gatedCommunity: true, budget: 13000, deposit: 26000, moveIn: '30', gender: 'female', food: 'veg', tags: ['Vegetarian', 'Non-smoker', 'Working professional'], note: 'Private room with attached bath on the first floor of an independent house in a gated lane. Terrace access, parking, quiet street.', img: ROOM_IMGS[0], verified: true, time: '1 day ago' },
];
const SEED_GROUPS = [
  { id: 'g1', title: '2 girls → need 1 more for a 2BHK in Baner', locality: 'Baner', policy: 'women', rent: 34000, seatsTotal: 3, members: [{ name: 'Riya', initials: 'RI', verified: true }, { name: 'Sneha', initials: 'SN', verified: true }], tags: ['Non-smoker', 'Working professional'], note: 'Working professionals, non-smokers. Move-in within a month.', time: '3 hours ago' },
  { id: 'g2', title: '3BHK near EON IT Park — 1 seat left', locality: 'Viman Nagar', policy: 'any', rent: 45000, seatsTotal: 3, members: [{ name: 'Aditya', initials: 'AD', verified: false }, { name: 'Karan', initials: 'KA', verified: true }], tags: ['Non-veg ok', 'Working professional'], note: 'Two engineers, chill crowd. Close to EON / WTC Kharadi.', time: '1 day ago' },
  { id: 'g3', title: 'Looking for 1 flatmate, 2BHK in Wakad', locality: 'Wakad', policy: 'men', rent: 28000, seatsTotal: 2, members: [{ name: 'Rahul', initials: 'RA', verified: false }], tags: ['Vegetarian', 'Non-smoker'], note: 'Veg, quiet, WFO at Hinjawadi.', time: '2 days ago' },
  { id: 'g4', title: 'Premium 2BHK in Kalyani Nagar to split', locality: 'Kalyani Nagar', policy: 'any', rent: 50000, seatsTotal: 2, members: [{ name: 'Karan', initials: 'KA', verified: true }], tags: ['Pet-friendly', 'Fitness'], note: 'Pet-friendly, gym in building.', time: '4 days ago' },
  { id: 'g5', title: 'Girls 2BHK share near Aundh', locality: 'Aundh', policy: 'women', rent: 32000, seatsTotal: 3, members: [{ name: 'Ananya', initials: 'AN', verified: true }, { name: 'Meera', initials: 'ME', verified: true }], tags: ['Vegetarian', 'Pet-friendly'], note: 'Plants & cats welcome. Long-term preferred.', time: '5 days ago' },
];

export { LOCALITIES, TAGS, MOVE_LBL, FLAT_PREF_LBL, ROOM_PREF_LBL, MOVE_RANK, LOCALITY_COORDS, ROOM_IMGS, SEEKERS, SEED_ROOMS, SEED_GROUPS };
