// Drive both photo uploads through the wizard so hashing and wire mapping cannot be bypassed.
// Different addresses isolate photo matching from address matching.
import { test, expect, ACTORS } from '../../../fixtures/live.js';
import { pickDate } from '../../../helpers/datePicker.helper.js';
import { uniquePhotoPng, uploadPublishablePhotos } from '../../../helpers/listingPhotos.helper.js';
import { signIn, signedInAsNew, authHeaders, API } from '../../../helpers/liveAuth.js';
// Kunal has one listing against two slots, so quota cannot mask the duplicate guard.
const KUNAL = '9700000090';
const KUNAL_LISTING = 'd0000000-0000-4000-8000-0000000000d1';

// A different unit and society leave the meter as the only shared identity signal.
const KUNAL_FLAT_RESPELLED = 'c 701';
const KUNAL_SOCIETY_RESPELLED = 'Dup Guard Residency Society';
const KUNAL_STREET_RESPELLED = 'baner road';
// Only synthetic owners are cleaned up; Kunal's shared seed must remain intact.
const owners = new Set();

test.afterEach(async () => {
  if (!owners.size) return;
  const adminHeaders = await authHeaders(ACTORS.admin);
  for (const mobile of owners) {
    const res = await fetch(`${API}/me/listings`, { headers: await authHeaders(mobile) });
    if (res.status !== 200) continue;
    const body = await res.json();
    const rows = Array.isArray(body) ? body : (body.content ?? body.items ?? []);
    for (const row of rows) {
      await fetch(`${API}/properties/${row.id}/status`, {
        method: 'PATCH',
        headers: adminHeaders,
        body: JSON.stringify({ status: 'rejected', reason: 'Zztest cleanup \u2014 synthetic dup-modal fixture' }),
      });
    }
  }
  owners.clear();
});

async function pickOption(page, dataErr, label) {
  await page.locator(`[data-err="${dataErr}"]`).click();
  await expect(page.locator('.dz-dropdown__menu.is-portal-open')).toBeVisible();
  await page.locator('.dz-dropdown__option', { hasText: label }).first().click();
}

// Let each caller assert its own submit outcome: duplicate block or successful post.
async function driveTheWizard(page, { flat, society, street, locality = 'Baner', duplicate = false, photo }) {
  await page.goto('/list-property');
  await page.waitForSelector('.lp-steps', { timeout: 20000 });

  await page.locator('.radio-pill', { hasText: 'Rent' }).first().click();
  await pickOption(page, 'propertyType', 'Flat / Apartment');
  await page.locator('[data-err="bhk"]').getByRole('button', { name: '2', exact: true }).click();
  await page.locator('input[data-err="carpetArea"]').fill('900');
  for (const [dataErr, value] of [['floor', '9'], ['totalFloors', '14']]) {
    await page.locator(`[data-err="${dataErr}"] .dz-dropdown__trigger`).click();
    await expect(page.locator('.dz-dropdown__menu.is-portal-open')).toBeVisible();
    await page.getByRole('option', { name: value, exact: true }).click();
  }
  await page.getByRole('button', { name: /Next Step/i }).click();
  await page.waitForSelector('.gm-style', { timeout: 30000 });

  await pickOption(page, 'locality', locality);
  await page.locator('input[data-err="flatNumber"]').fill(flat);
  await page.locator('input[data-err="society"]').fill(society);
  if (street) await page.locator('input[data-err="street"]').fill(street);
  await page.locator('input[data-err="pincode"]').fill('411045');
  const duplicateCheck = duplicate
    ? page.waitForResponse((res) => res.url().includes('/me/listings/duplicate-check') && res.request().method() === 'POST')
    : null;
  await page.getByRole('button', { name: /Next Step/i }).click();
  if (duplicateCheck) {
    expect((await (await duplicateCheck).json()).found).toBe(true);
    return;
  }
  await page.waitForSelector('text=/Price & terms/i', { timeout: 15000 });
  await page.locator('input[data-err="monthlyRent"]').fill('30000');
  await page.locator('input[data-err="deposit"]').fill('60000');
  await pickDate(page, '[data-err="availableFrom"]', '2027-12-31');
  await page.getByRole('button', { name: /Next Step/i }).click();
  await page.waitForSelector('text=/Photos & description/i', { timeout: 15000 });

  // Both owners upload identical canvas-generated bytes so the photo hash can match across sessions.
  await uploadPublishablePhotos(page, photo ? { buffer: photo } : {});
  await page.getByRole('button', { name: /Submit Property/i }).click();
}

async function myListings(mobile) {
  const res = await fetch(`${API}/me/listings`, { headers: await authHeaders(mobile) });
  expect(res.status).toBe(200);
  const body = await res.json();
  return Array.isArray(body) ? body : (body.content ?? body.items ?? []);
}

test.describe('LIVE — posting a flat the owner has already listed', () => {
  test('the same address stops a second post, however it is spelled', async ({ page }) => {
    await signIn(page, KUNAL);

    const before = await myListings(KUNAL);
    expect(before).toHaveLength(1);
    expect(before[0].id).toBe(KUNAL_LISTING);

    await driveTheWizard(page, {
      flat: KUNAL_FLAT_RESPELLED,
      society: KUNAL_SOCIETY_RESPELLED,
      street: KUNAL_STREET_RESPELLED,
      duplicate: true,
    });

    await expect(page.getByText(/already listed this property/i)).toBeVisible({ timeout: 20000 });
    await expect(page.getByRole('button', { name: /Go to my existing listing/i })).toBeVisible();
    await expect(page.locator('text=/Submitted for review/i')).toHaveCount(0);
    // A visible modal alone cannot prove the server rejected the write.
    expect(await myListings(KUNAL)).toHaveLength(1);
    // Pin the destination to the server's existing listing rather than any editor route.
    await page.getByRole('button', { name: /Go to my existing listing/i }).click();
    await expect(page).toHaveURL(new RegExp(`edit=${KUNAL_LISTING}`), { timeout: 10000 });
  });

  test('a photograph uploaded in the wizard reaches the server as a comparable hash', async ({ page, browser }) => {
    test.setTimeout(240_000);

    const photo = uniquePhotoPng();
    const first = await signedInAsNew(page);
    owners.add(first);
    await driveTheWizard(page, { flat: 'P-1', society: 'ZZ Photo Wire One', locality: 'Kothrud', photo });
    await expect(page.locator('text=/Submitted for review/i')).toBeVisible({ timeout: 30000 });
    const [firstListing] = await myListings(first);
    expect(firstListing).toBeTruthy();
    // Isolate sessions because photo reuse is checked across owners, not within one account.
    const second = await browser.newContext();
    const page2 = await second.newPage();
    let secondMobile;
    try {
      secondMobile = await signedInAsNew(page2);
      owners.add(secondMobile);
      // A different society in a different locality: the address arm is blind here by construction,
      // so a note about this listing can only have come from the photograph.
      await driveTheWizard(page2, { flat: 'Q-9', society: 'ZZ Photo Wire Two', locality: 'Wakad', photo });
      await expect(page2.locator('text=/Submitted for review/i')).toBeVisible({ timeout: 30000 });
    } finally {
      await second.close();
    }

    const [secondListing] = await myListings(secondMobile);
    expect(secondListing).toBeTruthy();
    // Staff can read internal findings; the listing owner must not learn which signals tripped review.
    const admin = await authHeaders(ACTORS.admin);
    const res = await fetch(`${API}/properties/${secondListing.id}/verification`, { headers: admin });
    expect(res.status, 'a case file exists on the second listing, so something was filed about it').toBe(200);
    const file = await res.json();
    const photoNote = (file.messages || []).find((m) => /reuses photographs/.test(m.body || ''));
    expect(photoNote, 'the photo arm filed a note naming the earlier listing').toBeTruthy();
    expect(photoNote.internal).toBe(true);
    expect(photoNote.body).toContain(firstListing.id);
  });
});
