// Drive both photo uploads through the wizard so hashing and wire mapping cannot be bypassed.
// Different addresses isolate photo matching from address matching.
import { test, expect, ACTORS } from '../../../fixtures/live.js';
import { pickDate } from '../../../helpers/datePicker.helper.js';
import { uploadPublishablePhotos } from '../../../helpers/listingPhotos.helper.js';
import { signIn, signedInAsNew, authHeaders, API } from '../../../helpers/liveAuth.js';

const PNG =
  'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAARElEQVR4AeyROw0AIAxEL5WADzSw4AcRaGLBDzqKg7uhS4c2eVOTy33snemMtrYzDMErASBBB/0OMNTKCSIoi+pfEYAPAAD//68o26gAAAAGSURBVAMAR8QwUeUtYucAAAAASUVORK5CYII=';

// Kunal has one listing against two slots, so quota cannot mask the duplicate guard.
const KUNAL = '9700000090';
const KUNAL_LISTING = 'd0000000-0000-4000-8000-0000000000d1';

// Respace the seeded meter to exercise normalization rather than literal equality.
const KUNAL_METER_RESPELLED = '1700-4455-6677';

// A different unit and society leave the meter as the only shared identity signal.
const OTHER_FLAT = 'A-101';
const OTHER_SOCIETY = 'ZZ Different Society Entirely';

// Only synthetic owners are cleaned up; Kunal's shared seed must remain intact.
const owners = new Set();

// Rejection removes synthetic photographs from the duplicate probe's occupying set.
test.afterEach(async () => {
  if (!owners.size) return;
  const adminHeaders = await authHeaders(ACTORS.admin);
  for (const mobile of owners) {
    const res = await fetch(`${API}/me/listings`, { headers: await authHeaders(mobile) });
    if (res.status !== 200) continue;
    const body = await res.json();
    const rows = Array.isArray(body) ? body : (body.content ?? body.items ?? []);
    for (const row of rows) {
      await fetch(`${API}/properties/${row.id}/status`, {
        method: 'PATCH',
        headers: adminHeaders,
        body: JSON.stringify({ status: 'rejected', reason: 'Zztest cleanup \u2014 synthetic dup-modal fixture' }),
      });
    }
  }
  owners.clear();
});

async function pickOption(page, dataErr, label) {
  await page.locator(`[data-err="${dataErr}"]`).click();
  // Portal mounting precedes interactivity by one animation frame.
  await expect(page.locator('.dz-dropdown__menu.is-portal-open')).toBeVisible();
  await page.locator('.dz-dropdown__option', { hasText: label }).first().click();
}

// Let each caller assert its own submit outcome: duplicate block or successful post.
async function driveTheWizard(page, { flat, society, locality = 'Baner', meter }) {
  await page.goto('/list-property');
  // The step rail distinguishes the wizard from the paywall, which also renders the meter.
  await page.waitForSelector('.lp-steps', { timeout: 20000 });

  // Rent needs fewer gating answers while carrying the same duplicate signals.
  await page.locator('.radio-pill', { hasText: 'Rent' }).first().click();
  await pickOption(page, 'propertyType', 'Flat / Apartment');
  await page.locator('input[data-err="carpetArea"]').fill('900');
  for (const [dataErr, value] of [['floor', '9'], ['totalFloors', '14']]) {
    await page.locator(`[data-err="${dataErr}"] .dz-dropdown__trigger`).click();
    await expect(page.locator('.dz-dropdown__menu.is-portal-open')).toBeVisible();
    await page.getByRole('option', { name: value, exact: true }).click();
  }
  await page.getByRole('button', { name: /Next Step/i }).click();
  await page.waitForSelector('.gm-style', { timeout: 30000 });

  await pickOption(page, 'locality', locality);
  await page.locator('input[data-err="flatNumber"]').fill(flat);
  await page.locator('input[data-err="society"]').fill(society);
  await page.locator('input[data-err="pincode"]').fill('411045');
  await page.getByRole('button', { name: /Next Step/i }).click();
  await page.waitForSelector('text=/Price & terms/i', { timeout: 15000 });
  await page.locator('input[data-err="monthlyRent"]').fill('30000');
  await page.locator('input[data-err="deposit"]').fill('60000');
  await pickDate(page, '[data-err="availableFrom"]', '2027-12-31');
  await page.getByRole('button', { name: /Next Step/i }).click();
  await page.waitForSelector('text=/Photos & documents/i', { timeout: 15000 });

  if (meter) {
    await page.getByPlaceholder(/MSEDCL electricity bill/i).fill(meter);
  }

  // Both owners upload identical canvas-generated bytes so the photo hash can match across sessions.
  const buf = Buffer.from(PNG, 'base64');
  await uploadPublishablePhotos(page);
  await page.locator('.doc-upload input[type="file"]').first()
    .setInputFiles({ name: 'doc.png', mimeType: 'image/png', buffer: buf });
  await page.getByRole('button', { name: /Submit Property/i }).click();
}

async function myListings(mobile) {
  const res = await fetch(`${API}/me/listings`, { headers: await authHeaders(mobile) });
  expect(res.status).toBe(200);
  const body = await res.json();
  return Array.isArray(body) ? body : (body.content ?? body.items ?? []);
}

test.describe('LIVE — posting a flat the owner has already listed', () => {
  test('the meter number stops a second post, even under a different address', async ({ page }) => {
    await signIn(page, KUNAL);

    const before = await myListings(KUNAL);
    // A free slot makes the eventual block attributable to duplication rather than quota.
    expect(before).toHaveLength(1);
    expect(before[0].id).toBe(KUNAL_LISTING);

    await driveTheWizard(page, {
      flat: OTHER_FLAT,
      society: OTHER_SOCIETY,
      meter: KUNAL_METER_RESPELLED,
    });

    await expect(page.getByText(/already listed this property/i)).toBeVisible({ timeout: 20000 });
    await expect(page.getByRole('button', { name: /Go to my existing listing/i })).toBeVisible();
    await expect(page.locator('text=/Listed Successfully/i')).toHaveCount(0);

    // A visible modal alone cannot prove the server rejected the write.
    expect(await myListings(KUNAL)).toHaveLength(1);

    // Pin the destination to the server's existing listing rather than any editor route.
    await page.getByRole('button', { name: /Go to my existing listing/i }).click();
    await expect(page).toHaveURL(new RegExp(`edit=${KUNAL_LISTING}`), { timeout: 10000 });
  });

  test('a photograph uploaded in the wizard reaches the server as a comparable hash', async ({ page, browser }) => {
    // Two full wizard drives plus two sign-ins; the per-test default is not enough.
    test.setTimeout(240_000);

    const first = await signedInAsNew(page);
    owners.add(first);
    await driveTheWizard(page, { flat: 'P-1', society: 'ZZ Photo Wire One', locality: 'Kothrud' });
    await expect(page.locator('text=/Listed Successfully/i')).toBeVisible({ timeout: 30000 });
    const [firstListing] = await myListings(first);
    expect(firstListing).toBeTruthy();

    // Isolate sessions because photo reuse is checked across owners, not within one account.
    const second = await browser.newContext();
    const page2 = await second.newPage();
    let secondMobile;
    try {
      secondMobile = await signedInAsNew(page2);
      owners.add(secondMobile);
      // A different society in a different locality: the address arm is blind here by construction,
      // so a note about this listing can only have come from the photograph.
      await driveTheWizard(page2, { flat: 'Q-9', society: 'ZZ Photo Wire Two', locality: 'Wakad' });
      await expect(page2.locator('text=/Listed Successfully/i')).toBeVisible({ timeout: 30000 });
    } finally {
      await second.close();
    }

    const [secondListing] = await myListings(secondMobile);
    expect(secondListing).toBeTruthy();

    // Staff can read internal findings; the listing owner must not learn which signals tripped review.
    const admin = await authHeaders(ACTORS.admin);
    const res = await fetch(`${API}/properties/${secondListing.id}/verification`, { headers: admin });
    expect(res.status, 'a case file exists on the second listing, so something was filed about it').toBe(200);
    const file = await res.json();
    const photoNote = (file.messages || []).find((m) => /reuses photographs/.test(m.body || ''));
    expect(photoNote, 'the photo arm filed a note naming the earlier listing').toBeTruthy();
    expect(photoNote.internal).toBe(true);
    expect(photoNote.body).toContain(firstListing.id);
  });
});
