package com.draazy.api.catalog;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.draazy.api.billing.plan.TestPlanGrants;
import com.draazy.api.catalog.property.Property;
import com.draazy.api.catalog.property.PropertyPossession;
import com.draazy.api.catalog.property.PropertyRepository;
import com.draazy.api.catalog.property.PropertyStatus;
import com.draazy.api.identity.user.User;
import com.draazy.api.identity.user.UserRepository;
import com.draazy.api.support.AbstractApiTest;
import jakarta.persistence.EntityManager;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

/** Every facet must be a real SQL predicate, or paging and ordering silently answer the wrong set.
 * Score cases pin exact integers because a weighting is a product decision, not an implementation detail. */
@DisplayName("Listings search — filtering, scoring and ranking, in SQL")
class ListingSearchTest extends AbstractApiTest {

    @Autowired
    UserRepository users;
    @Autowired
    PropertyRepository properties;
    @Autowired
    EntityManager em;
    @Autowired
    TestPlanGrants grants;

    private User seller;

    @BeforeEach
    void seedOwner() {
        seller = new User(String.format("9%09d", System.nanoTime() % 1_000_000_000L), "owner");
        seller.setName("Search Owner");
        seller.setMobileVerified(true);
        seller = users.saveAndFlush(seller);
    }

    private Property rent(String title) {
        Property p = new Property(seller, title, "rent", "apartment", 25000L, "Kothrud", "Pune");
        p.setBhk(new BigDecimal("2"));
        p.setPriceUnit("per-month");
        p.setStatus(PropertyStatus.APPROVED);
        return p;
    }

    private Property buy(String title) {
        Property p = new Property(seller, title, "buy", "apartment", 9000000L, "Baner", "Pune");
        p.setBhk(new BigDecimal("3"));
        p.setPriceUnit("total");
        p.setStatus(PropertyStatus.APPROVED);
        return p;
    }

    /** Round-trips through the database: {@code quality_score} is generated, so the in-memory
     * instance a save returns has {@code null} there and would assert nothing. */
    private Property persist(Property p) {
        Property saved = properties.saveAndFlush(p);
        em.flush();
        em.clear();
        return properties.findById(saved.getId()).orElseThrow();
    }

    @Nested
    @DisplayName("quality score (V94) — generated by the database, to the point")
    class QualityScore {

        @Test
        @DisplayName("an empty listing scores zero, and is not rescued by having been posted")
        void emptyListingScoresZero() {
            assertThat(persist(rent("Bare")).getQualityScore()).isZero();
        }

        @Test
        @DisplayName("a rent listing scores each block exactly as specified")
        void rentScoreIsExact() {
            Property p = rent("Complete");
            p.setImages(List.of("a", "b", "c"));
            p.setDescription("x".repeat(200));
            p.setOwnerVerified(true);
            p.verifyOwnership(Instant.now(), null);
            p.setFurnishing("furnished");
            p.setFacing("east");
            p.setFloor(3);
            p.setPossession("ready-to-move");
            p.setDeposit(50000L);
            p.setAmenities(List.of("lift", "parking", "gym", "pool", "security"));

            assertThat(persist(p).getQualityScore()).isEqualTo((short) 100);
        }

        @Test
        @DisplayName("the cover image counts as one photo when there is no gallery")
        void coverImageIsAPhoto() {
            Property p = rent("Cover only");
            p.setCoverImage("https://example.test/cover.jpg");

            assertThat(persist(p).getQualityScore()).isEqualTo((short) 8);
        }

        @Test
        @DisplayName("unfurnished is a real answer, but a smaller one than furnished")
        void unfurnishedScoresLessThanFurnished() {
            Property bare = rent("Unfurnished");
            bare.setFurnishing("unfurnished");
            Property done = rent("Furnished");
            done.setFurnishing("furnished");

            // 3 against 5: stating "unfurnished" is information a seeker can act on, so it cannot
            // score zero; it also does not make the listing as complete as one that is furnished.
            assertThat(persist(bare).getQualityScore()).isEqualTo((short) 3);
            assertThat(persist(done).getQualityScore()).isEqualTo((short) 5);
        }

        @Test
        @DisplayName("a buy listing scores its own blocks — paperwork replaces the owner check")
        void buyScoreIsExact() {
            Property p = buy("Complete sale");
            p.setImages(List.of("a", "b", "c"));
            p.setDescription("x".repeat(200));
            p.verifyOwnership(Instant.now(), null);
            p.setDocsCount(3);
            p.setFurnishing("furnished");
            p.setFacing("east");
            p.setFloor(3);
            p.setTotalFloors(12);
            p.setArea(new BigDecimal("1200"));
            p.setPossession("ready-to-move");
            p.setAmenities(List.of("lift", "parking", "gym", "pool", "security"));

            assertThat(persist(p).getQualityScore()).isEqualTo((short) 100);
        }

        @Test
        @DisplayName("the score follows an edit with nothing to recompute")
        void scoreFollowsTheListing() {
            Property p = persist(rent("Growing"));
            assertThat(p.getQualityScore()).isZero();

            p.setImages(List.of("a", "b", "c"));

            // No recompute call anywhere in this test, deliberately: the entire argument for a
            // generated column over a maintained one is that there is no call to forget.
            assertThat(persist(p).getQualityScore()).isEqualTo((short) 25);
        }
    }

    @Nested
    @DisplayName("freshness — derived from the clock, so it can never be stored")
    class FreshnessTier {

        private String tierOf(Instant confirmed) throws Exception {
            Property p = rent("Freshness " + System.nanoTime());
            p.confirmAvailable(confirmed);
            Property saved = persist(p);
            return mvc.perform(get("/properties/" + saved.getId()))
                    .andExpect(status().isOk())
                    .andReturn().getResponse().getContentAsString()
                    .replaceAll("(?s).*\"freshness\"\\s*:\\s*\"([a-z]+)\".*", "$1");
        }

        @Test
        @DisplayName("each boundary lands on the tier it names")
        void boundariesAreInclusive() throws Exception {
            Instant now = Instant.now();
            assertThat(tierOf(now)).isEqualTo("active");
            assertThat(tierOf(now.minus(7, ChronoUnit.DAYS))).isEqualTo("active");
            assertThat(tierOf(now.minus(8, ChronoUnit.DAYS))).isEqualTo("aging");
            assertThat(tierOf(now.minus(14, ChronoUnit.DAYS))).isEqualTo("aging");
            assertThat(tierOf(now.minus(15, ChronoUnit.DAYS))).isEqualTo("stale");
            assertThat(tierOf(now.minus(30, ChronoUnit.DAYS))).isEqualTo("stale");
            assertThat(tierOf(now.minus(31, ChronoUnit.DAYS))).isEqualTo("dormant");
        }

        @Test
        @DisplayName("a listing nobody has confirmed falls back to when it was posted")
        void neverConfirmedFallsBackToPosting() throws Exception {

            assertThat(tierOf(null)).isEqualTo("active");
        }
    }

    @Nested
    @DisplayName("the facets that had no column (V95)")
    class NewFacets {

        private long count(String query) throws Exception {
            return number(query, "totalElements");
        }

        private long unstated(String query) throws Exception {
            return number(query, "unstatedElements");
        }

        private long number(String query, String field) throws Exception {
            String body = mvc.perform(get("/properties?" + query))
                    .andExpect(status().isOk())
                    .andReturn().getResponse().getContentAsString();
            return Long.parseLong(body.replaceAll("(?s).*\"" + field + "\"\\s*:\\s*(\\d+).*", "$1"));
        }

        @Test
        @DisplayName("an owner who stated no tenant preference matches every tenant filter")
        void emptyTenantsMatchesNoFilter() throws Exception {
            Property silent = rent("No preference stated");
            Property picky = rent("Family only");
            picky.setTenants(List.of("family"));
            Property other = rent("Company only");
            other.setTenants(List.of("company"));
            persist(silent);
            persist(picky);
            persist(other);

            assertThat(count("tenants=family&owner=" + seller.getId())).isEqualTo(2);
            assertThat(count("tenants=company&owner=" + seller.getId())).isEqualTo(2);
        }

        @Test
        @DisplayName("the move-in filter is cumulative — a month also takes what is free today")
        void availableFromIsCumulative() throws Exception {
            Property now = rent("Free today");
            now.setAvailableFrom("now");
            Property fortnight = rent("Free in a fortnight");
            fortnight.setAvailableFrom("15");
            Property month = rent("Free in a month");
            month.setAvailableFrom("30");
            persist(now);
            persist(fortnight);
            persist(month);

            String owner = "&owner=" + seller.getId();
            assertThat(count("availableFrom=now" + owner)).isEqualTo(1);
            assertThat(count("availableFrom=15" + owner)).isEqualTo(2);
            assertThat(count("availableFrom=30" + owner)).isEqualTo(3);
        }

        @Test
        @DisplayName("an unknown move-in bucket matches nothing rather than everything")
        void unknownBucketMatchesNothing() throws Exception {
            persist(rent("Anything"));

            // Answering an unrecognised value with the whole catalogue is the failure that looks
            // most like success.
            assertThat(count("availableFrom=whenever&owner=" + seller.getId())).isZero();
        }

        @Test
        @DisplayName("a facet whose every token is rejected returns nothing, not everything")
        void unsanitisableTokensMatchNothing() throws Exception {
            persist(rent("Ordinary"));

            // An empty token list must not read as an unused facet: that would answer a filter
            // nobody could match with the whole catalogue.
            String owner = "&owner=" + seller.getId();
            assertThat(count("localities=%27%20or%201%3D1--" + owner)).isZero();

            assertThat(count("amenities=%27%20or%201%3D1--" + owner)).isZero();
            assertThat(count("tenants=%27%20or%201%3D1--" + owner)).isZero();
        }

        @Test
        @DisplayName("the reserved construction token matches nothing, not everything")
        void unmatchableConstructionMatchesNothing() throws Exception {
            Property ready = rent("Ready to move");
            ready.setPossession(PropertyPossession.READY_TO_MOVE);
            persist(ready);
            persist(rent("Possession unstated"));

            // `PATTERN` is composed from the three possession constants, so admitting a fourth
            // state spelled this way fails here first.
            assertThat(PropertyPossession.UNMATCHABLE.matches(PropertyPossession.PATTERN)).isFalse();

            // Omitting the param instead means "not filtered", and `construction=` cannot say it:
            // an absent list param binds to an empty list too.
            String owner = "&owner=" + seller.getId();
            assertThat(count("construction=" + PropertyPossession.READY_TO_MOVE + owner)).isEqualTo(1);
            assertThat(count("construction=" + PropertyPossession.UNMATCHABLE + owner)).isZero();
        }

        @Test
        @DisplayName("an age bound keeps listings that never stated an age, and says how many")
        void anAgeBoundKeepsTheSilent() throws Exception {
            Property silent = rent("Age unstated");
            Property known = rent("Five years old");
            known.setAgeYears(5);
            persist(silent);
            persist(known);

            // Most of the catalogue never states an age, so a bound that deleted the silent rows
            // would discard the inventory it meant to narrow. They are kept and counted out instead.
            String owner = "&owner=" + seller.getId();
            assertThat(count("minAge=0&maxAge=10" + owner)).isEqualTo(2);
            assertThat(count("maxAge=3" + owner)).isEqualTo(1);
            assertThat(unstated("maxAge=3" + owner)).isEqualTo(1);

            // Nobody asked about age, so nothing is unstated with respect to the question.
            assertThat(unstated("owner=" + seller.getId())).isZero();
        }

        @Test
        @DisplayName("a floor bound keeps listings that never stated a floor, and says how many")
        void aFloorBoundKeepsTheSilent() throws Exception {
            Property silent = rent("Floor unstated");
            Property known = rent("Third floor");
            known.setFloor(3);
            persist(silent);
            persist(known);

            String owner = "&owner=" + seller.getId();
            assertThat(count("minFloor=5" + owner)).isEqualTo(1);
            assertThat(unstated("minFloor=5" + owner)).isEqualTo(1);

            // Both columns asked: the subset is their union over the match, not their sum - the
            // silent row is silent on both and must still be counted once.
            assertThat(count("minFloor=1&maxAge=3" + owner)).isEqualTo(2);
            assertThat(unstated("minFloor=1&maxAge=3" + owner)).isEqualTo(2);
        }

        @Test
        @DisplayName("an area bound keeps listings that never stated an area, and says how many")
        void anAreaBoundKeepsTheSilent() throws Exception {
            Property silent = rent("Area unstated");
            silent.setArea(null);
            Property known = rent("Nine hundred");
            known.setArea(new BigDecimal("900"));
            persist(silent);
            persist(known);

            // The column is nullable and `ListingCreate.area` carries no `@NotNull`, so a silent
            // row is a real stored state and must answer a NULL as age and floor do.
            String owner = "&owner=" + seller.getId();
            assertThat(count("minArea=1000" + owner)).isEqualTo(1);
            assertThat(unstated("minArea=1000" + owner)).isEqualTo(1);
        }

        @Test
        @DisplayName("a deposit bound keeps rentals that never stated a deposit, and says how many")
        void aDepositBoundKeepsTheSilent() throws Exception {
            Property silent = rent("Deposit unstated");
            Property known = rent("Two lakh deposit");
            known.setDeposit(200000L);
            persist(silent);
            persist(known);

            // A rental silent on the deposit has not thereby offered a zero, so it survives a
            // low-deposit search rather than being counted as the cheapest thing on the page.
            String owner = "&owner=" + seller.getId();
            assertThat(count("maxDeposit=100000" + owner)).isEqualTo(1);
            assertThat(unstated("maxDeposit=100000" + owner)).isEqualTo(1);
            assertThat(count("minDeposit=150000&maxDeposit=250000" + owner)).isEqualTo(2);

            // Bounds that exclude the only stated deposit leave the silent row and nothing else.
            assertThat(count("minDeposit=900000" + owner)).isEqualTo(1);
            assertThat(unstated("owner=" + seller.getId())).isZero();
        }

            // Equality, not negation: a blank brokerage column cannot back
            // the "no brokerage" claim, so the silent row stays hidden.
        @Test
        @DisplayName("room shape, zoning and pets each narrow on their own column")
        void remainingFacetsNarrow() throws Exception {
            Property share = rent("Room in a shared flat");
            share.setRoom("shared");
            share.setPets(true);
            Property plot = buy("Farm plot");
            plot.setLandUse("agricultural");
            persist(share);
            persist(plot);

            String owner = "&owner=" + seller.getId();
            assertThat(count("room=shared" + owner)).isEqualTo(1);
            assertThat(count("pets=true" + owner)).isEqualTo(1);
            assertThat(count("landUse=agricultural" + owner)).isEqualTo(1);

            assertThat(count("pets=false" + owner)).isEqualTo(2);
        }

        @Test
        @DisplayName("amenities AND — two ticks are two requirements, not two alternatives")
        void amenitiesAreConjunctive() throws Exception {
            Property both = rent("Lift and parking");
            both.setAmenities(List.of("lift", "parking"));
            Property one = rent("Lift only");
            one.setAmenities(List.of("lift"));
            persist(both);
            persist(one);

            String owner = "&owner=" + seller.getId();
            assertThat(count("amenities=lift" + owner)).isEqualTo(2);
            assertThat(count("amenities=lift,parking" + owner)).isEqualTo(1);
        }

        @Test
        @DisplayName("a BHK chip may be an open top — 3plus does not hide the 4BHKs")
        void bhkPlusIsARange() throws Exception {
            Property two = rent("Two bed");
            Property four = rent("Four bed");
            four.setBhk(new BigDecimal("4"));
            persist(two);
            persist(four);

            String owner = "&owner=" + seller.getId();
            assertThat(count("bhks=2" + owner)).isEqualTo(1);
            assertThat(count("bhks=3plus" + owner)).isEqualTo(1);
            assertThat(count("bhks=2,3plus" + owner)).isEqualTo(2);
        }
    }

    @Nested
    @DisplayName("W2 search facets — stated claims, JSONB filters and normalized area")
    class W2Facets {

        private long count(String query) throws Exception {
            return number(query, "totalElements");
        }

        private long unstated(String query) throws Exception {
            return number(query, "unstatedElements");
        }

        private long number(String query, String field) throws Exception {
            String body = mvc.perform(get("/properties?" + query))
                    .andExpect(status().isOk())
                    .andReturn().getResponse().getContentAsString();
            return Long.parseLong(body.replaceAll("(?s).*\"" + field + "\"\\s*:\\s*(\\d+).*", "$1"));
        }

        @Test
        @DisplayName("facing is a stated claim and excludes silence when asked")
        void facingNarrowsAndExcludesSilence() throws Exception {
            Property east = rent("East facing");
            east.setFacing("east");
            Property west = rent("West facing");
            west.setFacing("west");
            persist(east);
            persist(west);
            persist(rent("Facing unstated"));

            String owner = "&owner=" + seller.getId();
            assertThat(count("facing=East" + owner)).isEqualTo(1);
            assertThat(count("facing=EAST,sideways" + owner)).isEqualTo(1);
            assertThat(unstated("facing=East" + owner)).isZero();
        }

        @Test
        @DisplayName("a cardinal also matches the two corners beside it, which older listings may state")
        void cardinalMatchesAdjacentCorners() throws Exception {
            Property northEast = rent("North-East facing");
            northEast.setFacing("North-East");
            Property southWest = rent("South-West facing");
            southWest.setFacing("South-West");
            persist(northEast);
            persist(southWest);

            String owner = "&owner=" + seller.getId();
            assertThat(count("facing=North" + owner)).isEqualTo(1);
            assertThat(count("facing=east" + owner)).isEqualTo(1);
            assertThat(count("facing=North,West" + owner)).isEqualTo(2);
            assertThat(count("facing=South-East" + owner)).isZero();
        }

        @Test
        @DisplayName("oversized CSV facets match nothing instead of silently dropping tokens")
        void oversizedCsvFacetMatchesNothing() throws Exception {
            Property east = rent("East facing");
            east.setFacing("east");
            persist(east);

            String tooMany = String.join(",", Collections.nCopies(17, "east"));
            assertThat(count("facing=" + tooMany + "&owner=" + seller.getId())).isZero();
        }

        @Test
        @DisplayName("bathroom minimum keeps silence and counts it as unstated")
        void minimumBathroomsKeepsSilence() throws Exception {
            Property silent = rent("Baths unstated");
            Property one = rent("One bath");
            one.setBathrooms(1);
            Property two = rent("Two baths");
            two.setBathrooms(2);
            persist(silent);
            persist(one);
            persist(two);

            String owner = "&owner=" + seller.getId();
            assertThat(count("minBaths=2" + owner)).isEqualTo(2);
            assertThat(unstated("minBaths=2" + owner)).isEqualTo(1);
            assertThat(count("minBaths=0" + owner)).isEqualTo(3);
        }

        @Test
        @DisplayName("a photo minimum counts the gallery, so the reels feed needs no client filter")
        void minimumPhotosCountsTheGallery() throws Exception {
            Property bare = rent("Two photos");
            bare.setImages(List.of("a", "b"));
            Property tour = rent("Three photos");
            tour.setImages(List.of("a", "b", "c"));
            persist(bare);
            persist(tour);

            String owner = "&owner=" + seller.getId();
            assertThat(count("minPhotos=3" + owner)).isEqualTo(1);
            assertThat(count("minPhotos=0" + owner)).isEqualTo(2);
        }

        @Test
        @DisplayName("food narrows to the owner's veg / jain rule, and non-veg excludes both")
        void foodPreferenceNarrowsThroughJsonb() throws Exception {
            Property veg = rent("Veg only");
            veg.setFormDetails(Map.of("food", "veg"));
            Property legacyVeg = rent("Legacy veg only");
            legacyVeg.setFormDetails(Map.of("foodPref", "veg"));
            Property jain = rent("Jain only");
            jain.setFormDetails(Map.of("food", "jain"));
            Property nonVeg = rent("Non veg okay");
            nonVeg.setFormDetails(Map.of("food", "nonveg"));
            persist(veg);
            persist(legacyVeg);
            persist(jain);
            persist(nonVeg);
            persist(rent("Food unstated"));

            String owner = "&owner=" + seller.getId();
            assertThat(count("food=nonveg" + owner)).isEqualTo(2);
            assertThat(count("food=veg" + owner)).isEqualTo(2);
            assertThat(count("food=jain" + owner)).isEqualTo(1);
            assertThat(count("food=halal" + owner)).isEqualTo(5);
        }

        @Test
        @DisplayName("commercial JSONB facets narrow on shell and pre-lease state")
        void commercialJsonFacetsNarrow() throws Exception {
            Property bare = buy("Bare shell office");
            bare.setFormDetails(Map.of("shellType", "bareShell", "tenancyStatus", "leased"));
            Property warm = buy("Warm shell office");
            warm.setFormDetails(Map.of("shellType", "warmShell", "tenancyStatus", "vacant"));
            persist(bare);
            persist(warm);

            String owner = "&owner=" + seller.getId();
            assertThat(count("shell=bareShell,unknown" + owner)).isEqualTo(1);
            assertThat(count("preLeased=true" + owner)).isEqualTo(1);
            assertThat(count("preLeased=false" + owner)).isEqualTo(2);
        }

        @Test
        @DisplayName("NA status narrows through JSONB")
        void naStatusNarrows() throws Exception {
            Property sanctioned = buy("Sanctioned NA plot");
            sanctioned.setFormDetails(Map.of("naStatus", "sanctioned"));
            Property deemed = buy("Deemed NA plot");
            deemed.setFormDetails(Map.of("naStatus", "deemed"));
            persist(sanctioned);
            persist(deemed);
            persist(buy("NA unstated"));

            String owner = "&owner=" + seller.getId();
            assertThat(count("na=sanctioned" + owner)).isEqualTo(1);
            assertThat(count("na=sanctioned,deemed,bogus" + owner)).isEqualTo(2);
        }

        @Test
        @DisplayName("area filters compare square feet regardless of the stored unit")
        void areaBoundsNormalizeStoredUnits() throws Exception {
            Property acre = buy("One acre farm");
            acre.setArea(new BigDecimal("1"));
            acre.setAreaUnit("acre");
            Property small = buy("One thousand square feet");
            small.setArea(new BigDecimal("1000"));
            small.setAreaUnit("sqft");
            Property silent = buy("Area unstated");
            silent.setArea(null);
            persist(acre);
            persist(small);
            persist(silent);

            String owner = "&owner=" + seller.getId();
            assertThat(count("minArea=43000&maxArea=44000" + owner)).isEqualTo(2);
            assertThat(unstated("minArea=43000&maxArea=44000" + owner)).isEqualTo(1);
        }
    }

    @Nested
    @DisplayName("near a point — a circle, without PostGIS")
    class NearPoint {

        private long count(String query) throws Exception {
            String body = mvc.perform(get("/properties?" + query))
                    .andExpect(status().isOk())
                    .andReturn().getResponse().getContentAsString();
            return Long.parseLong(body.replaceAll("(?s).*\"totalElements\"\\s*:\\s*(\\d+).*", "$1"));
        }

        @Test
        @DisplayName("the radius is a circle, not the box used to find it")
        void cornersAreTrimmed() throws Exception {

            double lat = 18.5204;
            double lng = 73.8567;

            Property near = rent("Two km north");
            near.setLat(lat + 0.018);
            near.setLng(lng);

            // ~4km north AND ~4km east: inside a 5km bounding box on both axes, but ~5.7km away on
            // the diagonal. This is the listing a box-only implementation wrongly returns.
            Property corner = rent("On the diagonal");
            corner.setLat(lat + 0.036);
            corner.setLng(lng + 0.038);

            persist(near);
            persist(corner);

            String owner = "&owner=" + seller.getId();
            assertThat(count("nearLat=" + lat + "&nearLng=" + lng + "&nearRadiusKm=5" + owner))
                    .isEqualTo(1);
            assertThat(count("nearLat=" + lat + "&nearLng=" + lng + "&nearRadiusKm=10" + owner))
                    .isEqualTo(2);
        }

        @Test
        @DisplayName("a centre without a radius is an incomplete question, and is ignored")
        void incompleteNearPointIsIgnored() throws Exception {
            Property anywhere = rent("Somewhere");
            anywhere.setLat(18.52);
            anywhere.setLng(73.85);
            persist(anywhere);

            assertThat(count("nearLat=18.52&owner=" + seller.getId())).isEqualTo(1);
        }

        @Test
        @DisplayName("an absurd radius is clamped, not honoured — and not rejected either")
        void radiusIsClamped() throws Exception {
            Property pune = rent("In Pune");
            pune.setLat(18.5204);
            pune.setLng(73.8567);
            Property faraway = rent("In Delhi");
            faraway.setLat(28.6139);
            faraway.setLng(77.2090);
            persist(pune);
            persist(faraway);

            // 20,000km would otherwise size a bounding box spanning the planet, on an endpoint
            // anybody can call without signing in. Clamped to 50km, Delhi stays out.
            String owner = "&owner=" + seller.getId();
            assertThat(count("nearLat=18.5204&nearLng=73.8567&nearRadiusKm=20000" + owner))
                    .isEqualTo(1);
        }
    }

    @Nested
    @DisplayName("ranking — merit by default, and never over a buyer's own choice")
    class Ranking {

        private final String tag = "rank" + System.nanoTime();

        private Property featuredRent(String title) {
            User payer = new User(String.format("8%09d", System.nanoTime() % 1_000_000_000L), "owner");
            payer.setName("Paying Owner");
            payer.setMobileVerified(true);
            payer = users.saveAndFlush(payer);
            grants.grant(payer.getId(), TestPlanGrants.OWNER_PLUS);
            Property p = new Property(payer, title, "rent", "apartment", 25000L, tag, "Pune");
            p.setBhk(new BigDecimal("2"));
            p.setPriceUnit("per-month");
            p.setStatus(PropertyStatus.APPROVED);
            return p;
        }

        private Property plainRent(String title) {
            Property p = rent(title);
            p.setLocality(tag);
            return p;
        }

        private List<String> titles(String query) throws Exception {
            String body = mvc.perform(get("/properties?" + query))
                    .andExpect(status().isOk())
                    .andReturn().getResponse().getContentAsString();
            return java.util.regex.Pattern.compile("\"title\"\\s*:\\s*\"([^\"]+)\"")
                    .matcher(body).results().map(m -> m.group(1)).toList();
        }

        @Test
        @DisplayName("featured outranks every verification put together")
        void featuredDominates() throws Exception {
            Property plain = featuredRent("Featured but plain");
            Property decorated = plainRent("Verified and complete");
            decorated.setOwnerVerified(true);
            decorated.verifyOwnership(Instant.now(), null);
            decorated.setReraId("P52100012345");
            decorated.setImages(List.of("a", "b", "c"));
            persist(plain);
            persist(decorated);

            assertThat(titles("q=" + tag)).containsExactly(
                    "Featured but plain", "Verified and complete");
        }

        @Test
        @DisplayName("between equals, the more complete listing wins")
        void qualityBreaksTheTie() throws Exception {
            Property sparse = rent("Sparse");
            Property rich = rent("Rich");
            rich.setImages(List.of("a", "b", "c"));
            rich.setDescription("x".repeat(200));
            persist(sparse);
            persist(rich);

            assertThat(titles("owner=" + seller.getId())).containsExactly("Rich", "Sparse");
        }

        @Test
        @DisplayName("an explicit price sort is honoured — merit does not outrank the buyer")
        void explicitSortWins() throws Exception {
            Property dear = featuredRent("Dear and featured");
            dear.setPrice(90000L);
            Property cheap = plainRent("Cheap and plain");
            cheap.setPrice(5000L);
            persist(dear);
            persist(cheap);

            assertThat(titles("q=" + tag + "&sort=price,asc"))
                    .containsExactly("Cheap and plain", "Dear and featured");
        }

        @Test
        @DisplayName("rank=newest orders by recency, and does not re-sort by merit")
        void newestIgnoresMerit() throws Exception {
            Property older = rent("Older but excellent");
            older.setImages(List.of("a", "b", "c"));
            older.setDescription("x".repeat(200));
            persist(older);
            Property newer = rent("Newer and bare");
            persist(newer);

            assertThat(titles("owner=" + seller.getId() + "&rank=newest").getFirst())
                    .isEqualTo("Newer and bare");
        }

        @Test
        @DisplayName("rank=pricePerSqft orders by normalized area and leaves unstated area last")
        void pricePerSqftUsesNormalizedArea() throws Exception {
            Property cheap = buy("Cheap per sqft");
            cheap.setPrice(90_000L);
            cheap.setArea(new BigDecimal("100"));
            cheap.setAreaUnit("sqyd");
            Property costly = buy("Costly per sqft");
            costly.setPrice(1_000_000L);
            costly.setArea(new BigDecimal("100"));
            costly.setAreaUnit("sqft");
            Property unknown = buy("Unknown per sqft");
            unknown.setPrice(1L);
            unknown.setArea(null);
            persist(costly);
            persist(unknown);
            persist(cheap);

            assertThat(titles("owner=" + seller.getId() + "&rank=pricePerSqft"))
                    .containsExactly("Cheap per sqft", "Costly per sqft", "Unknown per sqft");
        }

        @Test
        @DisplayName("rank=verified puts verified rows before the default order")
        void verifiedRankGroupsVerifiedRowsFirst() throws Exception {
            Property featured = featuredRent("Featured but unverified");
            Property verified = plainRent("Verified but plain");
            verified.setOwnerVerified(true);
            persist(featured);
            persist(verified);

            assertThat(titles("q=" + tag + "&rank=verified").getFirst())
                    .isEqualTo("Verified but plain");
        }

        @Test
        @DisplayName("an unknown rank falls back to relevance")
        void unknownRankFallsBackToRelevance() throws Exception {
            Property plain = plainRent("Plain rank fallback");
            Property featured = featuredRent("Featured rank fallback");
            persist(plain);
            persist(featured);

            assertThat(titles("q=" + tag + "&rank=surprise").getFirst())
                    .isEqualTo("Featured rank fallback");
        }
    }

    @Nested
    @DisplayName("the public floor still holds under every new facet")
    class VisibilityFloor {

        @Test
        @DisplayName("a pending listing cannot be reached by any of the new filters")
        void newFacetsDoNotBypassTheFloor() throws Exception {
            Property hidden = rent("Awaiting moderation");
            hidden.setStatus(PropertyStatus.PENDING);
            hidden.setPets(true);
            hidden.setTenants(List.of("family"));
            hidden.setRoom("shared");
            persist(hidden);

            String owner = "&owner=" + seller.getId();
            mvc.perform(get("/properties?pets=true" + owner))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.totalElements").value(0));
            mvc.perform(get("/properties?tenants=family" + owner))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.totalElements").value(0));
            mvc.perform(get("/properties?room=shared" + owner))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.totalElements").value(0));
        }
    }
}
